<?php

namespace Framework\Classes\PhpWord\Collection;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:27:39.
 */
class AbstractCollectionTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var AbstractCollection
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new AbstractCollection;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Framework\Classes\PhpWord\Collection\AbstractCollection::getItems
     * @todo   Implement testGetItems().
     */
    public function testGetItems() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Collection\AbstractCollection::getItem
     * @todo   Implement testGetItem().
     */
    public function testGetItem() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Collection\AbstractCollection::setItem
     * @todo   Implement testSetItem().
     */
    public function testSetItem() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Collection\AbstractCollection::addItem
     * @todo   Implement testAddItem().
     */
    public function testAddItem() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Collection\AbstractCollection::countItems
     * @todo   Implement testCountItems().
     */
    public function testCountItems() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
