<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:33:07.
 */
class JSMin_UnterminatedRegExpExceptionTest extends PHPUnit_Framework_TestCase {

    /**
     * @var JSMin_UnterminatedRegExpException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new JSMin_UnterminatedRegExpException;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}
