<?php

namespace Framework\App;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:29:47.
 */
class AclTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Acl
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Acl(1);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Framework\App\Acl::Get_Config_Publico
     * @todo   Implement testGet_Config_Publico().
     */
    public function testGet_Config_Publico() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Acl::Get_Permissao_Nome
     * @todo   Implement testGet_Permissao_Nome().
     */
    public function testGet_Permissao_Nome() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Acl::getPermissao
     * @todo   Implement testGetPermissao().
     */
    public function testGetPermissao() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Acl::Get_Permissao_Chave
     * @todo   Implement testGet_Permissao_Chave().
     */
    public function testGet_Permissao_Chave() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Acl::Get_Permissao_Url
     * @todo   Implement testGet_Permissao_Url().
     */
    public function testGet_Permissao_Url() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Acl::Usuario_GetID
     * @todo   Implement testUsuario_GetID().
     */
    public function testUsuario_GetID() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Acl::Usuario_GetNome
     * @todo   Implement testUsuario_GetNome().
     */
    public function testUsuario_GetNome() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Acl::Usuario_GetEmail
     * @todo   Implement testUsuario_GetEmail().
     */
    public function testUsuario_GetEmail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Acl::Usuario_GetID_Static
     * @todo   Implement testUsuario_GetID_Static().
     */
    public function testUsuario_GetID_Static() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Acl::Usuario_Senha_Verificar
     * @todo   Implement testUsuario_Senha_Verificar().
     */
    public function testUsuario_Senha_Verificar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Acl::Usuario_Logar
     * @todo   Implement testUsuario_Logar().
     */
    public function testUsuario_Logar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Acl::Usuario_GetLogado
     * @todo   Implement testUsuario_GetLogado().
     */
    public function testUsuario_GetLogado() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Acl::Usuario_GetLogado_Static
     * @todo   Implement testUsuario_GetLogado_Static().
     */
    public function testUsuario_GetLogado_Static() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Acl::grupos_inserir
     * @todo   Implement testGrupos_inserir().
     */
    public function testGrupos_inserir() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Acl::Sistema_Modulos_Configs_Funcional
     * @todo   Implement testSistema_Modulos_Configs_Funcional().
     */
    public function testSistema_Modulos_Configs_Funcional() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Acl::Sistema_Modulos_Configs_Publico
     * @todo   Implement testSistema_Modulos_Configs_Publico().
     */
    public function testSistema_Modulos_Configs_Publico() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Acl::Sistema_Modulos_Carregar_Menu
     * @todo   Implement testSistema_Modulos_Carregar_Menu().
     */
    public function testSistema_Modulos_Carregar_Menu() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Acl::Sistema_Modulos_Carregar_Permissoes
     * @todo   Implement testSistema_Modulos_Carregar_Permissoes().
     */
    public function testSistema_Modulos_Carregar_Permissoes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Acl::Sistema_Modulos_Carregar_Funcional
     * @todo   Implement testSistema_Modulos_Carregar_Funcional().
     */
    public function testSistema_Modulos_Carregar_Funcional() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Acl::Sistema_Modulos_Carregar_Publico
     * @todo   Implement testSistema_Modulos_Carregar_Publico().
     */
    public function testSistema_Modulos_Carregar_Publico() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
