<?php

namespace Framework\App;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:29:44.
 */
class BootTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Boot
     */
    protected $object;
    protected $_Registro;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->_Registro    = &\Framework\App\Registro::getInstacia();
        $this->object     = &$this->_Registro->_Boot;
        
        // Inicializa Classes caso ainda nao tenham sido
        if ($this->object===false) {
            $this->_Registro->_Boot = new Boot();
        }
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Framework\App\Boot::Iniciar
     * @todo   Implement testIniciar().
     */
    public function testIniciar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Boot::Desligar
     * @todo   Implement testDesligar().
     */
    public function testDesligar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
