<?php

namespace Framework\App;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:29:46.
 */
class ControleTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Controle
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Controle;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Framework\App\Controle::Json_Definir_zerar
     * @todo   Implement testJson_Definir_zerar().
     */
    public function testJson_Definir_zerar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Controle::Tema_Endereco
     * @todo   Implement testTema_Endereco().
     */
    public function testTema_Endereco() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Controle::Enviar_Email
     * @todo   Implement testEnviar_Email().
     */
    public function testEnviar_Email() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Controle::Tema_Travar
     * @todo   Implement testTema_Travar().
     */
    public function testTema_Travar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Controle::Tema_Travar_GET
     * @todo   Implement testTema_Travar_GET().
     */
    public function testTema_Travar_GET() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Controle::Export_Download
     * @todo   Implement testExport_Download().
     */
    public function testExport_Download() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Controle::Gerador_Visualizar_Unidade
     * @todo   Implement testGerador_Visualizar_Unidade().
     */
    public function testGerador_Visualizar_Unidade() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Controle::Gerador_Formulario
     * @todo   Implement testGerador_Formulario().
     */
    public function testGerador_Formulario() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Controle::Gerador_Formulario_Janela
     * @todo   Implement testGerador_Formulario_Janela().
     */
    public function testGerador_Formulario_Janela() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Controle::DAO_Campos_TrocaID
     * @todo   Implement testDAO_Campos_TrocaID().
     */
    public function testDAO_Campos_TrocaID() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Controle::DAO_Campos_TrocaNOME
     * @todo   Implement testDAO_Campos_TrocaNOME().
     */
    public function testDAO_Campos_TrocaNOME() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Controle::DAO_Campos_RetiraAlternados
     * @todo   Implement testDAO_Campos_RetiraAlternados().
     */
    public function testDAO_Campos_RetiraAlternados() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Controle::DAO_Campos_TrocaAlternados
     * @todo   Implement testDAO_Campos_TrocaAlternados().
     */
    public function testDAO_Campos_TrocaAlternados() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Controle::DAO_Campos_AlternadosDesabilitados
     * @todo   Implement testDAO_Campos_AlternadosDesabilitados().
     */
    public function testDAO_Campos_AlternadosDesabilitados() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Controle::mysql_MudaLeitura
     * @todo   Implement testMysql_MudaLeitura().
     */
    public function testMysql_MudaLeitura() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Controle::DAO_RemoveLinkExtra
     * @todo   Implement testDAO_RemoveLinkExtra().
     */
    public function testDAO_RemoveLinkExtra() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Controle::DAO_Ext_Alterar
     * @todo   Implement testDAO_Ext_Alterar().
     */
    public function testDAO_Ext_Alterar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Controle::DAO_Ext_ADD
     * @todo   Implement testDAO_Ext_ADD().
     */
    public function testDAO_Ext_ADD() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Controle::mysql_AtualizaValor
     * @todo   Implement testMysql_AtualizaValor().
     */
    public function testMysql_AtualizaValor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Controle::mysql_AtualizaValores
     * @todo   Implement testMysql_AtualizaValores().
     */
    public function testMysql_AtualizaValores() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Controle::DAO_Campos_Retira
     * @todo   Implement testDAO_Campos_Retira().
     */
    public function testDAO_Campos_Retira() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Controle::__destruct
     * @todo   Implement test__destruct().
     */
    public function test__destruct() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Controle::Widget_Add
     * @todo   Implement testWidget_Add().
     */
    public function testWidget_Add() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
