<?php

namespace Framework\App;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:29:44.
 */
class RequestTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Request
     */
    protected $object;
    protected $_Registro;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->_Registro    = &\Framework\App\Registro::getInstacia();
        $this->object     = &$this->_Registro->_Request;
        
        // Inicializa Classes caso ainda nao tenham sido
        if($this->object===false){
            $this->_Registro->_Conexao = new Request();
        }
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Framework\App\Request::getURL
     * @todo   Implement testGetURL().
     */
    public function testGetURL() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Request::getModulo
     * @todo   Implement testGetModulo().
     */
    public function testGetModulo() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Request::getSubModulo
     * @todo   Implement testGetSubModulo().
     */
    public function testGetSubModulo() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Request::getMetodo
     * @todo   Implement testGetMetodo().
     */
    public function testGetMetodo() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Request::getArgs
     * @todo   Implement testGetArgs().
     */
    public function testGetArgs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Request::isAjax
     * @todo   Implement testIsAjax().
     */
    public function testIsAjax() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
