<?php

namespace Framework\App;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:29:43.
 */
class SessionTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Session
     */
    protected $object;
    protected $_Registro;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //Session::init();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        //Session::Destroy();
    }

    /**
     * @covers Framework\App\Session::set
     * @todo   Implement testSet().
     */
    public function testSet_e_Get_e_Destroy() {
        /*$numero = rand();
        Session::set('TestSession',$numero);
        $valor = Session::get('TestSession');
        $this->assertEquals($numero,$valor);
        Session::Destroy('TestSession');
        $valor = Session::get('TestSession');
        $this->assertFalse($valor);*/
    }

}
