<?php

namespace Framework\App;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:29:46.
 */
class Sistema_FuncoesTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Sistema_Funcoes
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Sistema_Funcoes;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Framework\App\Sistema_Funcoes::Redirect
     * @todo   Implement testRedirect().
     */
    public function testRedirect() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Sistema_Funcoes::Control_Arq_Ext
     * @todo   Implement testControl_Arq_Ext().
     */
    public function testControl_Arq_Ext() {
        $this->assertEquals('jpeg', Sistema_Funcoes::Control_Arq_Ext('jpe'));
        $this->assertEquals('mpeg', Sistema_Funcoes::Control_Arq_Ext('mpe'));
        $this->assertEquals('tiff', Sistema_Funcoes::Control_Arq_Ext('tif'));
    }

    /**
     * @covers Framework\App\Sistema_Funcoes::Letra_Aleatoria
     * @todo   Implement testLetra_Aleatoria().
     */
    public function testLetra_Aleatoria() {
        // Remove the following lines when you implement this test.
        $this->assertFalse(is_numeric(Sistema_Funcoes::Letra_Aleatoria(rand())));
        $this->assertFalse(is_null(Sistema_Funcoes::Letra_Aleatoria(rand())));
        $this->assertFalse(is_array(Sistema_Funcoes::Letra_Aleatoria(rand())));
        $this->assertTrue(is_string(Sistema_Funcoes::Letra_Aleatoria(rand())));
        $this->assertEquals(1, strlen(Sistema_Funcoes::Letra_Aleatoria(rand())));
    }

    /**
     * @covers Framework\App\Sistema_Funcoes::Letra_LinkDecode
     * @todo   Implement testLetra_LinkDecode().
     */
    public function testLetra_LinkDecode() {
        $this->assertEquals('À', Sistema_Funcoes::Letra_LinkDecode('%C3%80'));
        $this->assertEquals('Á', Sistema_Funcoes::Letra_LinkDecode('%C3%81'));
        $this->assertEquals('ó', Sistema_Funcoes::Letra_LinkDecode('%C3%B3'));
        $this->assertEquals('%C3%80', Sistema_Funcoes::Letra_LinkDecode('À',true));
        $this->assertEquals('%C3%81', Sistema_Funcoes::Letra_LinkDecode('Á',true));
        $this->assertEquals('%C3%B3', Sistema_Funcoes::Letra_LinkDecode('ó',true));
    }

    /**
     * @covers Framework\App\Sistema_Funcoes::Erro
     * @todo   Implement testErro().
     */
    public function testErro() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Sistema_Funcoes::DirReplace
     * @todo   Implement testDirReplace().
     */
    public function testDirReplace() {
        $this->assertEquals('pasta/pasta/pasta', Sistema_Funcoes::DirReplace('pasta-pasta-pasta'));
        $this->assertEquals('pasta-pasta-pasta', Sistema_Funcoes::DirReplace('pasta/pasta/pasta'));
    }

    /**
     * @covers Framework\App\Sistema_Funcoes::Url_Limpeza
     * @todo   Implement testUrl_Limpeza().
     */
    public function testUrl_Limpeza() {
        $this->assertEquals('php.net/manual/pt_BR/function.rand.php', Sistema_Funcoes::Url_Limpeza('http://php.net/manual/pt_BR/function.rand.php'));
        $this->assertEquals('ricardosierra.com.br', Sistema_Funcoes::Url_Limpeza('http://www.ricardosierra.com.br'));
    }

    /**
     * @covers Framework\App\Sistema_Funcoes::VersionPHP
     * @todo   Implement testVersionPHP().
     */
    public function testVersionPHP() {
        // Teste 1
        $versao = '5.4.6';
        if (strnatcmp(phpversion(),$versao) >= 0) $resultado = TRUE;
        else                                      $resultado = FALSE;
        $this->assertEquals($resultado, Sistema_Funcoes::VersionPHP($versao));
        // TEste 2
        $versao = '6.4.6';
        if (strnatcmp(phpversion(),$versao) >= 0) $resultado = TRUE;
        else                                      $resultado = FALSE;
        $this->assertEquals($resultado, Sistema_Funcoes::VersionPHP($versao));
        
    }

    /**
     * @covers Framework\App\Sistema_Funcoes::Transf_Object_Array
     * @todo   Implement testTransf_Object_Array().
     */
    public function testTransf_Object_Array() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Sistema_Funcoes::Perm_Modulos
     * @todo   Implement testPerm_Modulos().
     */
    public function testPerm_Modulos() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Sistema_Funcoes::Form_Senha_Blindar
     * @todo   Implement testForm_Senha_Blindar().
     */
    public function testForm_Senha_Blindar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Sistema_Funcoes::Seguranca_Usuario_Validar
     * @todo   Implement testSeguranca_Usuario_Validar().
     */
    public function testSeguranca_Usuario_Validar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Sistema_Funcoes::Seguranca_Gerar_Hash
     * @todo   Implement testSeguranca_Gerar_Hash().
     */
    public function testSeguranca_Gerar_Hash() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Sistema_Funcoes::Seguranca_Gerar_Token
     * @todo   Implement testSeguranca_Gerar_Token().
     */
    public function testSeguranca_Gerar_Token() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Sistema_Funcoes::HTML_min
     * @todo   Implement testHTML_min().
     */
    public function testHTML_min() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Sistema_Funcoes::Control_Layoult_Valida_Cep
     * @todo   Implement testControl_Layoult_Valida_Cep().
     */
    public function testControl_Layoult_Valida_Cep() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Sistema_Funcoes::Control_Layoult_Valida_Email
     * @todo   Implement testControl_Layoult_Valida_Email().
     */
    public function testControl_Layoult_Valida_Email() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Sistema_Funcoes::Tranf_Byte_Otimizado
     * @todo   Implement testTranf_Byte_Otimizado().
     */
    public function testTranf_Byte_Otimizado() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Sistema_Funcoes::Tranf_Otimizado_Byte
     * @todo   Implement testTranf_Otimizado_Byte().
     */
    public function testTranf_Otimizado_Byte() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Sistema_Funcoes::Tranf_Segundo_Tempo
     * @todo   Implement testTranf_Segundo_Tempo().
     */
    public function testTranf_Segundo_Tempo() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Sistema_Funcoes::Tranf_Tempo_Segundo
     * @todo   Implement testTranf_Tempo_Segundo().
     */
    public function testTranf_Tempo_Segundo() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Sistema_Funcoes::Tranf_Distancia_Otimizado
     * @todo   Implement testTranf_Distancia_Otimizado().
     */
    public function testTranf_Distancia_Otimizado() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Sistema_Funcoes::Tranf_Otimizado_Distancia
     * @todo   Implement testTranf_Otimizado_Distancia().
     */
    public function testTranf_Otimizado_Distancia() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Sistema_Funcoes::Tranf_Real_Float
     * @todo   Implement testTranf_Real_Float().
     */
    public function testTranf_Real_Float() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Sistema_Funcoes::Tranf_Float_Real
     * @todo   Implement testTranf_Float_Real().
     */
    public function testTranf_Float_Real() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Sistema_Funcoes::Tranf_Porc_Float
     * @todo   Implement testTranf_Porc_Float().
     */
    public function testTranf_Porc_Float() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Sistema_Funcoes::Tranf_Float_Porc
     * @todo   Implement testTranf_Float_Porc().
     */
    public function testTranf_Float_Porc() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Sistema_Funcoes::Modelo_Data_Soma
     * @todo   Implement testModelo_Data_Soma().
     */
    public function testModelo_Data_Soma() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Sistema_Funcoes::Get_Info_Data
     * @todo   Implement testGet_Info_Data().
     */
    public function testGet_Info_Data() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Sistema_Funcoes::Gerar_Senha
     * @todo   Implement testGerar_Senha().
     */
    public function testGerar_Senha() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Sistema_Funcoes::Detectar_Navegador
     * @todo   Implement testDetectar_Navegador().
     */
    public function testDetectar_Navegador() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Sistema_Funcoes::Get_Gps
     * @todo   Implement testGet_Gps().
     */
    public function testGet_Gps() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Sistema_Funcoes::Trans_Gps_Number
     * @todo   Implement testTrans_Gps_Number().
     */
    public function testTrans_Gps_Number() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
