<?php

namespace Framework\App;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:29:48.
 */
class VisualTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Visual
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = Array();
        
        $diretorio = dir(ROOT_PADRAO.'templates'.DS);
        // PRocura Arqiuvos e Anota valores usados
        while ($valor = $diretorio -> read()) {
            // Ignora Propria Pasta, pasta anterior e Arquivo Autoload
            if ($valor!='..' && $valor!='.') {
                $lay_CONF = ROOT_PADRAO.'templates'.DS.$valor.DS.'config'.DS;
                $this->assertTrue(file_exists($lay_CONF.'config.php'));
                require_once ($lay_CONF.'config.php');
                $this->object[] = new Visual(true,$valor);
            }
        }
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Framework\App\Visual::Javascript_Executar
     * @todo   Implement testJavascript_Executar().
     */
    public function testJavascript_Executar() {
        //$this->assertTrue(false);
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Visual::Bloco_Customizavel
     * @todo   Implement testBloco_Customizavel().
     */
    public function testBloco_Customizavel() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Visual::Bloco_Unico_CriaConteudo
     * @todo   Implement testBloco_Unico_CriaConteudo().
     */
    public function testBloco_Unico_CriaConteudo() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Visual::Bloco_Unico_CriaTitulo
     * @todo   Implement testBloco_Unico_CriaTitulo().
     */
    public function testBloco_Unico_CriaTitulo() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Visual::Bloco_Unico_Retornar
     * @todo   Implement testBloco_Unico_Retornar().
     */
    public function testBloco_Unico_Retornar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Visual::Bloco_Unico_CriaJanela
     * @todo   Implement testBloco_Unico_CriaJanela().
     */
    public function testBloco_Unico_CriaJanela() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Visual::Bloco_Maior_CriaConteudo
     * @todo   Implement testBloco_Maior_CriaConteudo().
     */
    public function testBloco_Maior_CriaConteudo() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Visual::Bloco_Maior_CriaTitulo
     * @todo   Implement testBloco_Maior_CriaTitulo().
     */
    public function testBloco_Maior_CriaTitulo() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Visual::Bloco_Maior_CriaJanela
     * @todo   Implement testBloco_Maior_CriaJanela().
     */
    public function testBloco_Maior_CriaJanela() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Visual::Bloco_Menor_CriaConteudo
     * @todo   Implement testBloco_Menor_CriaConteudo().
     */
    public function testBloco_Menor_CriaConteudo() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Visual::Bloco_Menor_CriaTitulo
     * @todo   Implement testBloco_Menor_CriaTitulo().
     */
    public function testBloco_Menor_CriaTitulo() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Visual::Bloco_Menor_CriaJanela
     * @todo   Implement testBloco_Menor_CriaJanela().
     */
    public function testBloco_Menor_CriaJanela() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Visual::janelaajax
     * @todo   Implement testJanelaajax().
     */
    public function testJanelaajax() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Visual::Blocar
     * @todo   Implement testBlocar().
     */
    public function testBlocar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Visual::Arquivos_Js_Dependencia
     * @todo   Implement testArquivos_Js_Dependencia().
     */
    public function testArquivos_Js_Dependencia() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Visual::Layoult_Abas_Carregar
     * @todo   Implement testLayoult_Abas_Carregar().
     */
    public function testLayoult_Abas_Carregar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Visual::Layoult_Home_Widgets_Add
     * @todo   Implement testLayoult_Home_Widgets_Add().
     */
    public function testLayoult_Home_Widgets_Add() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Visual::Layoult_Home_Widgets_Show
     * @todo   Implement testLayoult_Home_Widgets_Show().
     */
    public function testLayoult_Home_Widgets_Show() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Visual::Layoult_Abas_Ativar_JS
     * @todo   Implement testLayoult_Abas_Ativar_JS().
     */
    public function testLayoult_Abas_Ativar_JS() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Visual::Widget_Assimilar
     * @todo   Implement testWidget_Assimilar().
     */
    public function testWidget_Assimilar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Visual::Widgets_Assimilar
     * @todo   Implement testWidgets_Assimilar().
     */
    public function testWidgets_Assimilar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Visual::renderizar
     * @todo   Implement testRenderizar().
     */
    public function testRenderizar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Visual::Tema_Elementos_Btn
     * @todo   Implement testTema_Elementos_Btn().
     */
    public function testTema_Elementos_Btn() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Visual::renderizar_login
     * @todo   Implement testRenderizar_login().
     */
    public function testRenderizar_login() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Visual::renderizar_bloco
     * @todo   Implement testRenderizar_bloco().
     */
    public function testRenderizar_bloco() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Visual::Layolt_Tipo
     * @todo   Implement testLayolt_Tipo().
     */
    public function testLayolt_Tipo() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Visual::grafico_gerar
     * @todo   Implement testGrafico_gerar().
     */
    public function testGrafico_gerar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Visual::Show_Tabela_DataTable
     * @todo   Implement testShow_Tabela_DataTable().
     */
    public function testShow_Tabela_DataTable() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Visual::Show_Tabela_DataTable_Massiva
     * @todo   Implement testShow_Tabela_DataTable_Massiva().
     */
    public function testShow_Tabela_DataTable_Massiva() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Visual::Show_Upload
     * @todo   Implement testShow_Upload().
     */
    public function testShow_Upload() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Visual::Upload_Janela
     * @todo   Implement testUpload_Janela().
     */
    public function testUpload_Janela() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Visual::Js_Calendar_Gerar
     * @todo   Implement testJs_Calendar_Gerar().
     */
    public function testJs_Calendar_Gerar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Visual::Json_Start
     * @todo   Implement testJson_Start().
     */
    public function testJson_Start() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Visual::Json_Info_Update
     * @todo   Implement testJson_Info_Update().
     */
    public function testJson_Info_Update() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Visual::Json_Exist
     * @todo   Implement testJson_Exist().
     */
    public function testJson_Exist() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Visual::Json_ExisteTipo
     * @todo   Implement testJson_ExisteTipo().
     */
    public function testJson_ExisteTipo() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Visual::Json_RetiraTipo
     * @todo   Implement testJson_RetiraTipo().
     */
    public function testJson_RetiraTipo() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Visual::Json_IncluiTipo
     * @todo   Implement testJson_IncluiTipo().
     */
    public function testJson_IncluiTipo() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Visual::Json_Retorna
     * @todo   Implement testJson_Retorna().
     */
    public function testJson_Retorna() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Visual::Categorias_ShowTab
     * @todo   Implement testCategorias_ShowTab().
     */
    public function testCategorias_ShowTab() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Visual::Categorias_ShowSelect
     * @todo   Implement testCategorias_ShowSelect().
     */
    public function testCategorias_ShowSelect() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Visual::Categorias_ShowSelect_AJAX
     * @todo   Implement testCategorias_ShowSelect_AJAX().
     */
    public function testCategorias_ShowSelect_AJAX() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\App\Visual::Tema_Tipos
     * @todo   Implement testTema_Tipos().
     */
    public function testTema_Tipos() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
