<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:33:12.
 */
class Minify_DebugDetectorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Minify_DebugDetector
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Minify_DebugDetector;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Minify_DebugDetector::shouldDebugRequest
     * @todo   Implement testShouldDebugRequest().
     */
    public function testShouldDebugRequest() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
