<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:33:07.
 */
class Minify_SourceTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Minify_Source
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Minify_Source;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Minify_Source::getContent
     * @todo   Implement testGetContent().
     */
    public function testGetContent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Minify_Source::getId
     * @todo   Implement testGetId().
     */
    public function testGetId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Minify_Source::haveNoMinifyPrefs
     * @todo   Implement testHaveNoMinifyPrefs().
     */
    public function testHaveNoMinifyPrefs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Minify_Source::getDigest
     * @todo   Implement testGetDigest().
     */
    public function testGetDigest() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Minify_Source::getContentType
     * @todo   Implement testGetContentType().
     */
    public function testGetContentType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
