<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:33:14.
 */
class Minify_YUICompressorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Minify_YUICompressor
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Minify_YUICompressor;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Minify_YUICompressor::minifyJs
     * @todo   Implement testMinifyJs().
     */
    public function testMinifyJs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Minify_YUICompressor::minifyCss
     * @todo   Implement testMinifyCss().
     */
    public function testMinifyCss() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
