<?php

namespace Framework\Classes;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:29:34.
 */
class SierraTec_EstatisticaTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var SierraTec_Estatistica
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SierraTec_Estatistica;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Framework\Classes\SierraTec_Estatistica::Gera_Estatistica
     * @todo   Implement testGera_Estatistica().
     */
    public function testGera_Estatistica() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
