<?php

namespace Framework\Classes\PhpWord\Writer;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:28:51.
 */
class PDFTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var PDF
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PDF;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Framework\Classes\PhpWord\Writer\PDF::__call
     * @todo   Implement test__call().
     */
    public function test__call() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
