<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:27:34.
 */
class StageTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Stage
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Stage;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Stage::pass
     * @todo   Implement testPass().
     */
    public function testPass() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
