<?php

namespace MrClay\Cli;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:33:05.
 */
class ArgTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Arg
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Arg;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers MrClay\Cli\Arg::getDefaultSpec
     * @todo   Implement testGetDefaultSpec().
     */
    public function testGetDefaultSpec() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrClay\Cli\Arg::useAsOutfile
     * @todo   Implement testUseAsOutfile().
     */
    public function testUseAsOutfile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrClay\Cli\Arg::useAsInfile
     * @todo   Implement testUseAsInfile().
     */
    public function testUseAsInfile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrClay\Cli\Arg::getSpec
     * @todo   Implement testGetSpec().
     */
    public function testGetSpec() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrClay\Cli\Arg::setDescription
     * @todo   Implement testSetDescription().
     */
    public function testSetDescription() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrClay\Cli\Arg::getDescription
     * @todo   Implement testGetDescription().
     */
    public function testGetDescription() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrClay\Cli\Arg::isRequired
     * @todo   Implement testIsRequired().
     */
    public function testIsRequired() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrClay\Cli\Arg::__call
     * @todo   Implement test__call().
     */
    public function test__call() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrClay\Cli\Arg::__get
     * @todo   Implement test__get().
     */
    public function test__get() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
