<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:33:03.
 */
class HTTP_ConditionalGetTest extends PHPUnit_Framework_TestCase {

    /**
     * @var HTTP_ConditionalGet
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new HTTP_ConditionalGet;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers HTTP_ConditionalGet::getHeaders
     * @todo   Implement testGetHeaders().
     */
    public function testGetHeaders() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HTTP_ConditionalGet::setContentLength
     * @todo   Implement testSetContentLength().
     */
    public function testSetContentLength() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HTTP_ConditionalGet::sendHeaders
     * @todo   Implement testSendHeaders().
     */
    public function testSendHeaders() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HTTP_ConditionalGet::check
     * @todo   Implement testCheck().
     */
    public function testCheck() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HTTP_ConditionalGet::gmtDate
     * @todo   Implement testGmtDate().
     */
    public function testGmtDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
