<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:34:03.
 */
class PagSeguroConfigTest extends PHPUnit_Framework_TestCase {

    /**
     * @var PagSeguroConfig
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PagSeguroConfig;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers PagSeguroConfig::init
     * @todo   Implement testInit().
     */
    public function testInit() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroConfig::getData
     * @todo   Implement testGetData().
     */
    public function testGetData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroConfig::setData
     * @todo   Implement testSetData().
     */
    public function testSetData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroConfig::setEnvironment
     * @todo   Implement testSetEnvironment().
     */
    public function testSetEnvironment() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroConfig::getApplicationCredentials
     * @todo   Implement testGetApplicationCredentials().
     */
    public function testGetApplicationCredentials() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroConfig::getAccountCredentials
     * @todo   Implement testGetAccountCredentials().
     */
    public function testGetAccountCredentials() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroConfig::getPaymentRedirectUrl
     * @todo   Implement testGetPaymentRedirectUrl().
     */
    public function testGetPaymentRedirectUrl() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroConfig::getStaticUrl
     * @todo   Implement testGetStaticUrl().
     */
    public function testGetStaticUrl() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroConfig::getEnvironment
     * @todo   Implement testGetEnvironment().
     */
    public function testGetEnvironment() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroConfig::getApplicationCharset
     * @todo   Implement testGetApplicationCharset().
     */
    public function testGetApplicationCharset() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroConfig::setApplicationCharset
     * @todo   Implement testSetApplicationCharset().
     */
    public function testSetApplicationCharset() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroConfig::logIsActive
     * @todo   Implement testLogIsActive().
     */
    public function testLogIsActive() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroConfig::activeLog
     * @todo   Implement testActiveLog().
     */
    public function testActiveLog() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroConfig::getLogFileLocation
     * @todo   Implement testGetLogFileLocation().
     */
    public function testGetLogFileLocation() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroConfig::validateRequirements
     * @todo   Implement testValidateRequirements().
     */
    public function testValidateRequirements() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
