<?php

namespace Framework\Classes\PhpWord\Exception;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:29:05.
 */
class ExceptionTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Exception
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Exception;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}
