<?php

namespace Framework\Classes;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:29:35.
 */
class TextoTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Texto
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Texto;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Framework\Classes\Texto::Transformar_Plural_Singular
     * @todo   Implement testTransformar_Plural_Singular().
     */
    public function testTransformar_Plural_Singular() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\Texto::Captura_Palavra_Masculina
     * @todo   Implement testCaptura_Palavra_Masculina().
     */
    public function testCaptura_Palavra_Masculina() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
