<?php

namespace MrClay;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:33:05.
 */
class CliTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Cli
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Cli;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers MrClay\Cli::addOptionalArg
     * @todo   Implement testAddOptionalArg().
     */
    public function testAddOptionalArg() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrClay\Cli::addRequiredArg
     * @todo   Implement testAddRequiredArg().
     */
    public function testAddRequiredArg() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrClay\Cli::addArgument
     * @todo   Implement testAddArgument().
     */
    public function testAddArgument() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrClay\Cli::getArgument
     * @todo   Implement testGetArgument().
     */
    public function testGetArgument() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrClay\Cli::validate
     * @todo   Implement testValidate().
     */
    public function testValidate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrClay\Cli::getPathArgs
     * @todo   Implement testGetPathArgs().
     */
    public function testGetPathArgs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrClay\Cli::getErrorReport
     * @todo   Implement testGetErrorReport().
     */
    public function testGetErrorReport() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrClay\Cli::getArgumentsListing
     * @todo   Implement testGetArgumentsListing().
     */
    public function testGetArgumentsListing() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrClay\Cli::openInput
     * @todo   Implement testOpenInput().
     */
    public function testOpenInput() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrClay\Cli::closeInput
     * @todo   Implement testCloseInput().
     */
    public function testCloseInput() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrClay\Cli::openOutput
     * @todo   Implement testOpenOutput().
     */
    public function testOpenOutput() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrClay\Cli::closeOutput
     * @todo   Implement testCloseOutput().
     */
    public function testCloseOutput() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
