<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:33:25.
 */
class PagSeguroAutoloaderTest extends PHPUnit_Framework_TestCase {

    /**
     * @var PagSeguroAutoloader
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PagSeguroAutoloader;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers PagSeguroAutoloader::init
     * @todo   Implement testInit().
     */
    public function testInit() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
