<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:34:00.
 */
class PagSeguroTransactionSearchServiceTest extends PHPUnit_Framework_TestCase {

    /**
     * @var PagSeguroTransactionSearchService
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PagSeguroTransactionSearchService;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers PagSeguroTransactionSearchService::searchByCode
     * @todo   Implement testSearchByCode().
     */
    public function testSearchByCode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransactionSearchService::searchByDate
     * @todo   Implement testSearchByDate().
     */
    public function testSearchByDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransactionSearchService::searchAbandoned
     * @todo   Implement testSearchAbandoned().
     */
    public function testSearchAbandoned() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransactionSearchService::searchByReference
     * @todo   Implement testSearchByReference().
     */
    public function testSearchByReference() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
