<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:33:58.
 */
class PagSeguroAuthorizationSearchServiceTest extends PHPUnit_Framework_TestCase {

    /**
     * @var PagSeguroAuthorizationSearchService
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PagSeguroAuthorizationSearchService;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers PagSeguroAuthorizationSearchService::searchByCode
     * @todo   Implement testSearchByCode().
     */
    public function testSearchByCode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroAuthorizationSearchService::searchByNotificationCode
     * @todo   Implement testSearchByNotificationCode().
     */
    public function testSearchByNotificationCode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroAuthorizationSearchService::searchAuthorizations
     * @todo   Implement testSearchAuthorizations().
     */
    public function testSearchAuthorizations() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroAuthorizationSearchService::searchByReference
     * @todo   Implement testSearchByReference().
     */
    public function testSearchByReference() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
