<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:33:58.
 */
class PagSeguroAuthorizationServiceTest extends PHPUnit_Framework_TestCase {

    /**
     * @var PagSeguroAuthorizationService
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PagSeguroAuthorizationService;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers PagSeguroAuthorizationService::createAuthorizationRequest
     * @todo   Implement testCreateAuthorizationRequest().
     */
    public function testCreateAuthorizationRequest() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
