<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:34:02.
 */
class PagSeguroNotificationServiceTest extends PHPUnit_Framework_TestCase {

    /**
     * @var PagSeguroNotificationService
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PagSeguroNotificationService;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers PagSeguroNotificationService::checkTransaction
     * @todo   Implement testCheckTransaction().
     */
    public function testCheckTransaction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroNotificationService::checkAuthorization
     * @todo   Implement testCheckAuthorization().
     */
    public function testCheckAuthorization() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
