<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:34:01.
 */
class PagSeguroConnectionDataTest extends PHPUnit_Framework_TestCase {

    /**
     * @var PagSeguroConnectionData
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PagSeguroConnectionData;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers PagSeguroConnectionData::getCredentials
     * @todo   Implement testGetCredentials().
     */
    public function testGetCredentials() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroConnectionData::setCredentials
     * @todo   Implement testSetCredentials().
     */
    public function testSetCredentials() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroConnectionData::getCredentialsUrlQuery
     * @todo   Implement testGetCredentialsUrlQuery().
     */
    public function testGetCredentialsUrlQuery() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroConnectionData::getEnvironment
     * @todo   Implement testGetEnvironment().
     */
    public function testGetEnvironment() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroConnectionData::setEnvironment
     * @todo   Implement testSetEnvironment().
     */
    public function testSetEnvironment() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroConnectionData::getWebserviceUrl
     * @todo   Implement testGetWebserviceUrl().
     */
    public function testGetWebserviceUrl() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroConnectionData::setWebserviceUrl
     * @todo   Implement testSetWebserviceUrl().
     */
    public function testSetWebserviceUrl() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroConnectionData::getPaymentUrl
     * @todo   Implement testGetPaymentUrl().
     */
    public function testGetPaymentUrl() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroConnectionData::setPaymentUrl
     * @todo   Implement testSetPaymentUrl().
     */
    public function testSetPaymentUrl() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroConnectionData::getBaseUrl
     * @todo   Implement testGetBaseUrl().
     */
    public function testGetBaseUrl() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroConnectionData::setBaseUrl
     * @todo   Implement testSetBaseUrl().
     */
    public function testSetBaseUrl() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroConnectionData::getInstallmentUrl
     * @todo   Implement testGetInstallmentUrl().
     */
    public function testGetInstallmentUrl() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroConnectionData::setInstallmentUrl
     * @todo   Implement testSetInstallmentUrl().
     */
    public function testSetInstallmentUrl() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroConnectionData::getAuthorizationUrl
     * @todo   Implement testGetAuthorizationUrl().
     */
    public function testGetAuthorizationUrl() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroConnectionData::setAuthorizationUrl
     * @todo   Implement testSetAuthorizationUrl().
     */
    public function testSetAuthorizationUrl() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroConnectionData::getSessionUrl
     * @todo   Implement testGetSessionUrl().
     */
    public function testGetSessionUrl() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroConnectionData::setSessionUrl
     * @todo   Implement testSetSessionUrl().
     */
    public function testSetSessionUrl() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroConnectionData::getServicePath
     * @todo   Implement testGetServicePath().
     */
    public function testGetServicePath() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroConnectionData::setServicePath
     * @todo   Implement testSetServicePath().
     */
    public function testSetServicePath() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroConnectionData::getServiceTimeout
     * @todo   Implement testGetServiceTimeout().
     */
    public function testGetServiceTimeout() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroConnectionData::setServiceTimeout
     * @todo   Implement testSetServiceTimeout().
     */
    public function testSetServiceTimeout() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroConnectionData::getServiceUrl
     * @todo   Implement testGetServiceUrl().
     */
    public function testGetServiceUrl() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroConnectionData::getResource
     * @todo   Implement testGetResource().
     */
    public function testGetResource() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroConnectionData::getCharset
     * @todo   Implement testGetCharset().
     */
    public function testGetCharset() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroConnectionData::setCharset
     * @todo   Implement testSetCharset().
     */
    public function testSetCharset() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
