<?php

namespace Framework\Classes;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:29:36.
 */
class SecurimageTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Securimage
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Securimage;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Framework\Classes\Securimage::getPath
     * @todo   Implement testGetPath().
     */
    public function testGetPath() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\Securimage::getCaptchaId
     * @todo   Implement testGetCaptchaId().
     */
    public function testGetCaptchaId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\Securimage::checkByCaptchaId
     * @todo   Implement testCheckByCaptchaId().
     */
    public function testCheckByCaptchaId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\Securimage::show
     * @todo   Implement testShow().
     */
    public function testShow() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\Securimage::check
     * @todo   Implement testCheck().
     */
    public function testCheck() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\Securimage::getCaptchaHtml
     * @todo   Implement testGetCaptchaHtml().
     */
    public function testGetCaptchaHtml() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\Securimage::getTimeToSolve
     * @todo   Implement testGetTimeToSolve().
     */
    public function testGetTimeToSolve() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\Securimage::setNamespace
     * @todo   Implement testSetNamespace().
     */
    public function testSetNamespace() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\Securimage::outputAudioFile
     * @todo   Implement testOutputAudioFile().
     */
    public function testOutputAudioFile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\Securimage::getCode
     * @todo   Implement testGetCode().
     */
    public function testGetCode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\Securimage::createCode
     * @todo   Implement testCreateCode().
     */
    public function testCreateCode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\Securimage::getRandomNoiseFile
     * @todo   Implement testGetRandomNoiseFile().
     */
    public function testGetRandomNoiseFile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\Securimage::frand
     * @todo   Implement testFrand().
     */
    public function testFrand() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\Securimage::errorHandler
     * @todo   Implement testErrorHandler().
     */
    public function testErrorHandler() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
