<?php

namespace Framework\Classes\PhpWord\Reader\Word2007;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:27:42.
 */
class AbstractPartTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var AbstractPart
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new AbstractPart;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Framework\Classes\PhpWord\Reader\Word2007\AbstractPart::setRels
     * @todo   Implement testSetRels().
     */
    public function testSetRels() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
