<?php

namespace Framework\Classes;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:29:32.
 */
class PagamentoTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Pagamento
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Pagamento;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Framework\Classes\Pagamento::getModulos
     * @todo   Implement testGetModulos().
     */
    public function testGetModulos() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\Pagamento::_Pagar
     * @todo   Implement test_Pagar().
     */
    public function test_Pagar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\Pagamento::_Retornar
     * @todo   Implement test_Retornar().
     */
    public function test_Retornar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
