<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:27:32.
 */
class Face_DetectorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Face_Detector
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Face_Detector;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Face_Detector::face_detect
     * @todo   Implement testFace_detect().
     */
    public function testFace_detect() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Face_Detector::toJpeg
     * @todo   Implement testToJpeg().
     */
    public function testToJpeg() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Face_Detector::toJson
     * @todo   Implement testToJson().
     */
    public function testToJson() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Face_Detector::getFace
     * @todo   Implement testGetFace().
     */
    public function testGetFace() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
