<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:33:41.
 */
class PagSeguroTransactionTest extends PHPUnit_Framework_TestCase {

    /**
     * @var PagSeguroTransaction
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PagSeguroTransaction;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers PagSeguroTransaction::getLastEventDate
     * @todo   Implement testGetLastEventDate().
     */
    public function testGetLastEventDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransaction::setLastEventDate
     * @todo   Implement testSetLastEventDate().
     */
    public function testSetLastEventDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransaction::getDate
     * @todo   Implement testGetDate().
     */
    public function testGetDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransaction::setDate
     * @todo   Implement testSetDate().
     */
    public function testSetDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransaction::getCode
     * @todo   Implement testGetCode().
     */
    public function testGetCode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransaction::setCode
     * @todo   Implement testSetCode().
     */
    public function testSetCode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransaction::getReference
     * @todo   Implement testGetReference().
     */
    public function testGetReference() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransaction::setReference
     * @todo   Implement testSetReference().
     */
    public function testSetReference() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransaction::getRecoveryCode
     * @todo   Implement testGetRecoveryCode().
     */
    public function testGetRecoveryCode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransaction::setRecoveryCode
     * @todo   Implement testSetRecoveryCode().
     */
    public function testSetRecoveryCode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransaction::getType
     * @todo   Implement testGetType().
     */
    public function testGetType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransaction::setType
     * @todo   Implement testSetType().
     */
    public function testSetType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransaction::getStatus
     * @todo   Implement testGetStatus().
     */
    public function testGetStatus() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransaction::setStatus
     * @todo   Implement testSetStatus().
     */
    public function testSetStatus() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransaction::getCancellationSource
     * @todo   Implement testGetCancellationSource().
     */
    public function testGetCancellationSource() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransaction::setCancellationSource
     * @todo   Implement testSetCancellationSource().
     */
    public function testSetCancellationSource() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransaction::getPaymentMethod
     * @todo   Implement testGetPaymentMethod().
     */
    public function testGetPaymentMethod() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransaction::setPaymentLink
     * @todo   Implement testSetPaymentLink().
     */
    public function testSetPaymentLink() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransaction::getPaymentLink
     * @todo   Implement testGetPaymentLink().
     */
    public function testGetPaymentLink() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransaction::setPaymentMethod
     * @todo   Implement testSetPaymentMethod().
     */
    public function testSetPaymentMethod() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransaction::getGrossAmount
     * @todo   Implement testGetGrossAmount().
     */
    public function testGetGrossAmount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransaction::setGrossAmount
     * @todo   Implement testSetGrossAmount().
     */
    public function testSetGrossAmount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransaction::getDiscountAmount
     * @todo   Implement testGetDiscountAmount().
     */
    public function testGetDiscountAmount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransaction::setDiscountAmount
     * @todo   Implement testSetDiscountAmount().
     */
    public function testSetDiscountAmount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransaction::getFeeAmount
     * @todo   Implement testGetFeeAmount().
     */
    public function testGetFeeAmount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransaction::setFeeAmount
     * @todo   Implement testSetFeeAmount().
     */
    public function testSetFeeAmount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransaction::getNetAmount
     * @todo   Implement testGetNetAmount().
     */
    public function testGetNetAmount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransaction::setNetAmount
     * @todo   Implement testSetNetAmount().
     */
    public function testSetNetAmount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransaction::getEscrowEndDate
     * @todo   Implement testGetEscrowEndDate().
     */
    public function testGetEscrowEndDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransaction::setEscrowEndDate
     * @todo   Implement testSetEscrowEndDate().
     */
    public function testSetEscrowEndDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransaction::getExtraAmount
     * @todo   Implement testGetExtraAmount().
     */
    public function testGetExtraAmount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransaction::setExtraAmount
     * @todo   Implement testSetExtraAmount().
     */
    public function testSetExtraAmount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransaction::getInstallmentCount
     * @todo   Implement testGetInstallmentCount().
     */
    public function testGetInstallmentCount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransaction::setInstallmentCount
     * @todo   Implement testSetInstallmentCount().
     */
    public function testSetInstallmentCount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransaction::setCreditorFees
     * @todo   Implement testSetCreditorFees().
     */
    public function testSetCreditorFees() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransaction::getCreditorFees
     * @todo   Implement testGetCreditorFees().
     */
    public function testGetCreditorFees() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransaction::setOperationalFeeAmount
     * @todo   Implement testSetOperationalFeeAmount().
     */
    public function testSetOperationalFeeAmount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransaction::getOperationalFeeAmount
     * @todo   Implement testGetOperationalFeeAmount().
     */
    public function testGetOperationalFeeAmount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransaction::setInstallmentFeeAmount
     * @todo   Implement testSetInstallmentFeeAmount().
     */
    public function testSetInstallmentFeeAmount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransaction::getInstallmentFeeAmount
     * @todo   Implement testGetInstallmentFeeAmount().
     */
    public function testGetInstallmentFeeAmount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransaction::getItems
     * @todo   Implement testGetItems().
     */
    public function testGetItems() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransaction::setItems
     * @todo   Implement testSetItems().
     */
    public function testSetItems() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransaction::getItemCount
     * @todo   Implement testGetItemCount().
     */
    public function testGetItemCount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransaction::getSender
     * @todo   Implement testGetSender().
     */
    public function testGetSender() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransaction::setSender
     * @todo   Implement testSetSender().
     */
    public function testSetSender() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransaction::getShipping
     * @todo   Implement testGetShipping().
     */
    public function testGetShipping() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransaction::setShipping
     * @todo   Implement testSetShipping().
     */
    public function testSetShipping() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransaction::toString
     * @todo   Implement testToString().
     */
    public function testToString() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
