<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:33:48.
 */
class PagSeguroAddressTest extends PHPUnit_Framework_TestCase {

    /**
     * @var PagSeguroAddress
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PagSeguroAddress;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers PagSeguroAddress::getStreet
     * @todo   Implement testGetStreet().
     */
    public function testGetStreet() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroAddress::getNumber
     * @todo   Implement testGetNumber().
     */
    public function testGetNumber() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroAddress::getComplement
     * @todo   Implement testGetComplement().
     */
    public function testGetComplement() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroAddress::getDistrict
     * @todo   Implement testGetDistrict().
     */
    public function testGetDistrict() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroAddress::getCity
     * @todo   Implement testGetCity().
     */
    public function testGetCity() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroAddress::getState
     * @todo   Implement testGetState().
     */
    public function testGetState() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroAddress::getPostalCode
     * @todo   Implement testGetPostalCode().
     */
    public function testGetPostalCode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroAddress::getCountry
     * @todo   Implement testGetCountry().
     */
    public function testGetCountry() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroAddress::setCountry
     * @todo   Implement testSetCountry().
     */
    public function testSetCountry() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroAddress::setStreet
     * @todo   Implement testSetStreet().
     */
    public function testSetStreet() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroAddress::setNumber
     * @todo   Implement testSetNumber().
     */
    public function testSetNumber() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroAddress::setComplement
     * @todo   Implement testSetComplement().
     */
    public function testSetComplement() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroAddress::setDistrict
     * @todo   Implement testSetDistrict().
     */
    public function testSetDistrict() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroAddress::setCity
     * @todo   Implement testSetCity().
     */
    public function testSetCity() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroAddress::setState
     * @todo   Implement testSetState().
     */
    public function testSetState() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroAddress::setPostalCode
     * @todo   Implement testSetPostalCode().
     */
    public function testSetPostalCode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
