<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:33:47.
 */
class PagSeguroAuthorizationSearchResultTest extends PHPUnit_Framework_TestCase {

    /**
     * @var PagSeguroAuthorizationSearchResult
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PagSeguroAuthorizationSearchResult;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers PagSeguroAuthorizationSearchResult::getCurrentPage
     * @todo   Implement testGetCurrentPage().
     */
    public function testGetCurrentPage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroAuthorizationSearchResult::setCurrentPage
     * @todo   Implement testSetCurrentPage().
     */
    public function testSetCurrentPage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroAuthorizationSearchResult::getDate
     * @todo   Implement testGetDate().
     */
    public function testGetDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroAuthorizationSearchResult::setDate
     * @todo   Implement testSetDate().
     */
    public function testSetDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroAuthorizationSearchResult::getResultsInThisPage
     * @todo   Implement testGetResultsInThisPage().
     */
    public function testGetResultsInThisPage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroAuthorizationSearchResult::setResultsInThisPage
     * @todo   Implement testSetResultsInThisPage().
     */
    public function testSetResultsInThisPage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroAuthorizationSearchResult::getTotalPages
     * @todo   Implement testGetTotalPages().
     */
    public function testGetTotalPages() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroAuthorizationSearchResult::setTotalPages
     * @todo   Implement testSetTotalPages().
     */
    public function testSetTotalPages() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroAuthorizationSearchResult::getAuthorizations
     * @todo   Implement testGetAuthorizations().
     */
    public function testGetAuthorizations() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroAuthorizationSearchResult::setAuthorizations
     * @todo   Implement testSetAuthorizations().
     */
    public function testSetAuthorizations() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroAuthorizationSearchResult::toString
     * @todo   Implement testToString().
     */
    public function testToString() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
