<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:33:32.
 */
class PagSeguroErrorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var PagSeguroError
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PagSeguroError;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers PagSeguroError::getCode
     * @todo   Implement testGetCode().
     */
    public function testGetCode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroError::setCode
     * @todo   Implement testSetCode().
     */
    public function testSetCode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroError::getMessage
     * @todo   Implement testGetMessage().
     */
    public function testGetMessage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroError::setMessage
     * @todo   Implement testSetMessage().
     */
    public function testSetMessage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
