<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:33:33.
 */
class PagSeguroCreditCardCheckoutTest extends PHPUnit_Framework_TestCase {

    /**
     * @var PagSeguroCreditCardCheckout
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PagSeguroCreditCardCheckout;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers PagSeguroCreditCardCheckout::setBrand
     * @todo   Implement testSetBrand().
     */
    public function testSetBrand() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroCreditCardCheckout::getBrand
     * @todo   Implement testGetBrand().
     */
    public function testGetBrand() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroCreditCardCheckout::setToken
     * @todo   Implement testSetToken().
     */
    public function testSetToken() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroCreditCardCheckout::getToken
     * @todo   Implement testGetToken().
     */
    public function testGetToken() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroCreditCardCheckout::setHolder
     * @todo   Implement testSetHolder().
     */
    public function testSetHolder() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroCreditCardCheckout::getHolder
     * @todo   Implement testGetHolder().
     */
    public function testGetHolder() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroCreditCardCheckout::setInstallment
     * @todo   Implement testSetInstallment().
     */
    public function testSetInstallment() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroCreditCardCheckout::getInstallment
     * @todo   Implement testGetInstallment().
     */
    public function testGetInstallment() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroCreditCardCheckout::setBilling
     * @todo   Implement testSetBilling().
     */
    public function testSetBilling() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroCreditCardCheckout::getBilling
     * @todo   Implement testGetBilling().
     */
    public function testGetBilling() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
