<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:33:49.
 */
class PagSeguroAuthorizationAccountTest extends PHPUnit_Framework_TestCase {

    /**
     * @var PagSeguroAuthorizationAccount
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PagSeguroAuthorizationAccount;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers PagSeguroAuthorizationAccount::getPrivateKey
     * @todo   Implement testGetPrivateKey().
     */
    public function testGetPrivateKey() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroAuthorizationAccount::setPrivateKey
     * @todo   Implement testSetPrivateKey().
     */
    public function testSetPrivateKey() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
