<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:33:40.
 */
class PagSeguroAuthorizationRequestTest extends PHPUnit_Framework_TestCase {

    /**
     * @var PagSeguroAuthorizationRequest
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PagSeguroAuthorizationRequest;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers PagSeguroAuthorizationRequest::setReference
     * @todo   Implement testSetReference().
     */
    public function testSetReference() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroAuthorizationRequest::getReference
     * @todo   Implement testGetReference().
     */
    public function testGetReference() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroAuthorizationRequest::setRedirectURL
     * @todo   Implement testSetRedirectURL().
     */
    public function testSetRedirectURL() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroAuthorizationRequest::getRedirectURL
     * @todo   Implement testGetRedirectURL().
     */
    public function testGetRedirectURL() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroAuthorizationRequest::setNotificationURL
     * @todo   Implement testSetNotificationURL().
     */
    public function testSetNotificationURL() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroAuthorizationRequest::getNotificationURL
     * @todo   Implement testGetNotificationURL().
     */
    public function testGetNotificationURL() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroAuthorizationRequest::getPermissions
     * @todo   Implement testGetPermissions().
     */
    public function testGetPermissions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroAuthorizationRequest::setPermissions
     * @todo   Implement testSetPermissions().
     */
    public function testSetPermissions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroAuthorizationRequest::setParameter
     * @todo   Implement testSetParameter().
     */
    public function testSetParameter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroAuthorizationRequest::getParameter
     * @todo   Implement testGetParameter().
     */
    public function testGetParameter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroAuthorizationRequest::addParameter
     * @todo   Implement testAddParameter().
     */
    public function testAddParameter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroAuthorizationRequest::addIndexedParameter
     * @todo   Implement testAddIndexedParameter().
     */
    public function testAddIndexedParameter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroAuthorizationRequest::register
     * @todo   Implement testRegister().
     */
    public function testRegister() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroAuthorizationRequest::toString
     * @todo   Implement testToString().
     */
    public function testToString() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroAuthorizationRequest::verifyURLTest
     * @todo   Implement testVerifyURLTest().
     */
    public function testVerifyURLTest() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
