<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:33:36.
 */
class PagSeguroNotificationTypeTest extends PHPUnit_Framework_TestCase {

    /**
     * @var PagSeguroNotificationType
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PagSeguroNotificationType;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers PagSeguroNotificationType::setValue
     * @todo   Implement testSetValue().
     */
    public function testSetValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroNotificationType::setByType
     * @todo   Implement testSetByType().
     */
    public function testSetByType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroNotificationType::getValue
     * @todo   Implement testGetValue().
     */
    public function testGetValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroNotificationType::getTypeFromValue
     * @todo   Implement testGetTypeFromValue().
     */
    public function testGetTypeFromValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
