<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:33:48.
 */
class PagSeguroTransactionSummaryTest extends PHPUnit_Framework_TestCase {

    /**
     * @var PagSeguroTransactionSummary
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PagSeguroTransactionSummary;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers PagSeguroTransactionSummary::getDate
     * @todo   Implement testGetDate().
     */
    public function testGetDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransactionSummary::setDate
     * @todo   Implement testSetDate().
     */
    public function testSetDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransactionSummary::getCode
     * @todo   Implement testGetCode().
     */
    public function testGetCode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransactionSummary::setCode
     * @todo   Implement testSetCode().
     */
    public function testSetCode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransactionSummary::getReference
     * @todo   Implement testGetReference().
     */
    public function testGetReference() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransactionSummary::setReference
     * @todo   Implement testSetReference().
     */
    public function testSetReference() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransactionSummary::getGrossAmount
     * @todo   Implement testGetGrossAmount().
     */
    public function testGetGrossAmount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransactionSummary::setGrossAmount
     * @todo   Implement testSetGrossAmount().
     */
    public function testSetGrossAmount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransactionSummary::getType
     * @todo   Implement testGetType().
     */
    public function testGetType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransactionSummary::setType
     * @todo   Implement testSetType().
     */
    public function testSetType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransactionSummary::getLastEventDate
     * @todo   Implement testGetLastEventDate().
     */
    public function testGetLastEventDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransactionSummary::setLastEventDate
     * @todo   Implement testSetLastEventDate().
     */
    public function testSetLastEventDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransactionSummary::getStatus
     * @todo   Implement testGetStatus().
     */
    public function testGetStatus() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransactionSummary::setStatus
     * @todo   Implement testSetStatus().
     */
    public function testSetStatus() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransactionSummary::getNetAmount
     * @todo   Implement testGetNetAmount().
     */
    public function testGetNetAmount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransactionSummary::setNetAmount
     * @todo   Implement testSetNetAmount().
     */
    public function testSetNetAmount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransactionSummary::getDiscountAmount
     * @todo   Implement testGetDiscountAmount().
     */
    public function testGetDiscountAmount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransactionSummary::setDiscountAmount
     * @todo   Implement testSetDiscountAmount().
     */
    public function testSetDiscountAmount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransactionSummary::getFeeAmount
     * @todo   Implement testGetFeeAmount().
     */
    public function testGetFeeAmount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransactionSummary::setFeeAmount
     * @todo   Implement testSetFeeAmount().
     */
    public function testSetFeeAmount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransactionSummary::getExtraAmount
     * @todo   Implement testGetExtraAmount().
     */
    public function testGetExtraAmount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransactionSummary::setExtraAmount
     * @todo   Implement testSetExtraAmount().
     */
    public function testSetExtraAmount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransactionSummary::setCancellationSource
     * @todo   Implement testSetCancellationSource().
     */
    public function testSetCancellationSource() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransactionSummary::getCancellationSource
     * @todo   Implement testGetCancellationSource().
     */
    public function testGetCancellationSource() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransactionSummary::setPaymentMethod
     * @todo   Implement testSetPaymentMethod().
     */
    public function testSetPaymentMethod() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransactionSummary::getPaymentMethod
     * @todo   Implement testGetPaymentMethod().
     */
    public function testGetPaymentMethod() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransactionSummary::getRecoveryCode
     * @todo   Implement testGetRecoveryCode().
     */
    public function testGetRecoveryCode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroTransactionSummary::setRecoveryCode
     * @todo   Implement testSetRecoveryCode().
     */
    public function testSetRecoveryCode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
