<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:33:30.
 */
class PagSeguroPhoneTest extends PHPUnit_Framework_TestCase {

    /**
     * @var PagSeguroPhone
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PagSeguroPhone;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers PagSeguroPhone::getAreaCode
     * @todo   Implement testGetAreaCode().
     */
    public function testGetAreaCode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroPhone::getNumber
     * @todo   Implement testGetNumber().
     */
    public function testGetNumber() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroPhone::setAreaCode
     * @todo   Implement testSetAreaCode().
     */
    public function testSetAreaCode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroPhone::setNumber
     * @todo   Implement testSetNumber().
     */
    public function testSetNumber() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroPhone::setFullPhone
     * @todo   Implement testSetFullPhone().
     */
    public function testSetFullPhone() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
