<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:33:47.
 */
class PagSeguroPaymentRequestTest extends PHPUnit_Framework_TestCase {

    /**
     * @var PagSeguroPaymentRequest
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PagSeguroPaymentRequest;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers PagSeguroPaymentRequest::getSender
     * @todo   Implement testGetSender().
     */
    public function testGetSender() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroPaymentRequest::setSender
     * @todo   Implement testSetSender().
     */
    public function testSetSender() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroPaymentRequest::setSenderName
     * @todo   Implement testSetSenderName().
     */
    public function testSetSenderName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroPaymentRequest::setSenderEmail
     * @todo   Implement testSetSenderEmail().
     */
    public function testSetSenderEmail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroPaymentRequest::setSenderPhone
     * @todo   Implement testSetSenderPhone().
     */
    public function testSetSenderPhone() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroPaymentRequest::getCurrency
     * @todo   Implement testGetCurrency().
     */
    public function testGetCurrency() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroPaymentRequest::setCurrency
     * @todo   Implement testSetCurrency().
     */
    public function testSetCurrency() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroPaymentRequest::getItems
     * @todo   Implement testGetItems().
     */
    public function testGetItems() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroPaymentRequest::setItems
     * @todo   Implement testSetItems().
     */
    public function testSetItems() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroPaymentRequest::addItem
     * @todo   Implement testAddItem().
     */
    public function testAddItem() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroPaymentRequest::addSenderDocument
     * @todo   Implement testAddSenderDocument().
     */
    public function testAddSenderDocument() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroPaymentRequest::getRedirectURL
     * @todo   Implement testGetRedirectURL().
     */
    public function testGetRedirectURL() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroPaymentRequest::setRedirectURL
     * @todo   Implement testSetRedirectURL().
     */
    public function testSetRedirectURL() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroPaymentRequest::getExtraAmount
     * @todo   Implement testGetExtraAmount().
     */
    public function testGetExtraAmount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroPaymentRequest::setExtraAmount
     * @todo   Implement testSetExtraAmount().
     */
    public function testSetExtraAmount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroPaymentRequest::getReference
     * @todo   Implement testGetReference().
     */
    public function testGetReference() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroPaymentRequest::setReference
     * @todo   Implement testSetReference().
     */
    public function testSetReference() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroPaymentRequest::getShipping
     * @todo   Implement testGetShipping().
     */
    public function testGetShipping() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroPaymentRequest::setShipping
     * @todo   Implement testSetShipping().
     */
    public function testSetShipping() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroPaymentRequest::setShippingAddress
     * @todo   Implement testSetShippingAddress().
     */
    public function testSetShippingAddress() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroPaymentRequest::setShippingType
     * @todo   Implement testSetShippingType().
     */
    public function testSetShippingType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroPaymentRequest::setShippingCost
     * @todo   Implement testSetShippingCost().
     */
    public function testSetShippingCost() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroPaymentRequest::getMaxAge
     * @todo   Implement testGetMaxAge().
     */
    public function testGetMaxAge() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroPaymentRequest::setMaxAge
     * @todo   Implement testSetMaxAge().
     */
    public function testSetMaxAge() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroPaymentRequest::getMaxUses
     * @todo   Implement testGetMaxUses().
     */
    public function testGetMaxUses() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroPaymentRequest::setMaxUses
     * @todo   Implement testSetMaxUses().
     */
    public function testSetMaxUses() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroPaymentRequest::getNotificationURL
     * @todo   Implement testGetNotificationURL().
     */
    public function testGetNotificationURL() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroPaymentRequest::setNotificationURL
     * @todo   Implement testSetNotificationURL().
     */
    public function testSetNotificationURL() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroPaymentRequest::setMetaData
     * @todo   Implement testSetMetaData().
     */
    public function testSetMetaData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroPaymentRequest::getMetaData
     * @todo   Implement testGetMetaData().
     */
    public function testGetMetaData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroPaymentRequest::addMetaData
     * @todo   Implement testAddMetaData().
     */
    public function testAddMetaData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroPaymentRequest::setParameter
     * @todo   Implement testSetParameter().
     */
    public function testSetParameter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroPaymentRequest::getParameter
     * @todo   Implement testGetParameter().
     */
    public function testGetParameter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroPaymentRequest::addParameter
     * @todo   Implement testAddParameter().
     */
    public function testAddParameter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroPaymentRequest::addIndexedParameter
     * @todo   Implement testAddIndexedParameter().
     */
    public function testAddIndexedParameter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroPaymentRequest::register
     * @todo   Implement testRegister().
     */
    public function testRegister() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroPaymentRequest::toString
     * @todo   Implement testToString().
     */
    public function testToString() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroPaymentRequest::verifyURLTest
     * @todo   Implement testVerifyURLTest().
     */
    public function testVerifyURLTest() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
