<?php

namespace Framework\Classes;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:27:34.
 */
class TabelaTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Tabela
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Tabela;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Framework\Classes\Tabela::addcabecario
     * @todo   Implement testAddcabecario().
     */
    public function testAddcabecario() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\Tabela::addcorpo
     * @todo   Implement testAddcorpo().
     */
    public function testAddcorpo() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\Tabela::retornatabela
     * @todo   Implement testRetornatabela().
     */
    public function testRetornatabela() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
