<?php

namespace Framework\Classes\PhpWord\Metadata;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:27:35.
 */
class CompatibilityTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Compatibility
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Compatibility;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Framework\Classes\PhpWord\Metadata\Compatibility::getOoxmlVersion
     * @todo   Implement testGetOoxmlVersion().
     */
    public function testGetOoxmlVersion() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Metadata\Compatibility::setOoxmlVersion
     * @todo   Implement testSetOoxmlVersion().
     */
    public function testSetOoxmlVersion() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
