<?php

namespace Framework\Classes\PhpWord\Metadata;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:27:35.
 */
class DocInfoTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var DocInfo
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new DocInfo;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Framework\Classes\PhpWord\Metadata\DocInfo::getCreator
     * @todo   Implement testGetCreator().
     */
    public function testGetCreator() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Metadata\DocInfo::setCreator
     * @todo   Implement testSetCreator().
     */
    public function testSetCreator() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Metadata\DocInfo::getLastModifiedBy
     * @todo   Implement testGetLastModifiedBy().
     */
    public function testGetLastModifiedBy() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Metadata\DocInfo::setLastModifiedBy
     * @todo   Implement testSetLastModifiedBy().
     */
    public function testSetLastModifiedBy() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Metadata\DocInfo::getCreated
     * @todo   Implement testGetCreated().
     */
    public function testGetCreated() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Metadata\DocInfo::setCreated
     * @todo   Implement testSetCreated().
     */
    public function testSetCreated() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Metadata\DocInfo::getModified
     * @todo   Implement testGetModified().
     */
    public function testGetModified() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Metadata\DocInfo::setModified
     * @todo   Implement testSetModified().
     */
    public function testSetModified() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Metadata\DocInfo::getTitle
     * @todo   Implement testGetTitle().
     */
    public function testGetTitle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Metadata\DocInfo::setTitle
     * @todo   Implement testSetTitle().
     */
    public function testSetTitle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Metadata\DocInfo::getDescription
     * @todo   Implement testGetDescription().
     */
    public function testGetDescription() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Metadata\DocInfo::setDescription
     * @todo   Implement testSetDescription().
     */
    public function testSetDescription() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Metadata\DocInfo::getSubject
     * @todo   Implement testGetSubject().
     */
    public function testGetSubject() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Metadata\DocInfo::setSubject
     * @todo   Implement testSetSubject().
     */
    public function testSetSubject() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Metadata\DocInfo::getKeywords
     * @todo   Implement testGetKeywords().
     */
    public function testGetKeywords() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Metadata\DocInfo::setKeywords
     * @todo   Implement testSetKeywords().
     */
    public function testSetKeywords() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Metadata\DocInfo::getCategory
     * @todo   Implement testGetCategory().
     */
    public function testGetCategory() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Metadata\DocInfo::setCategory
     * @todo   Implement testSetCategory().
     */
    public function testSetCategory() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Metadata\DocInfo::getCompany
     * @todo   Implement testGetCompany().
     */
    public function testGetCompany() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Metadata\DocInfo::setCompany
     * @todo   Implement testSetCompany().
     */
    public function testSetCompany() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Metadata\DocInfo::getManager
     * @todo   Implement testGetManager().
     */
    public function testGetManager() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Metadata\DocInfo::setManager
     * @todo   Implement testSetManager().
     */
    public function testSetManager() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Metadata\DocInfo::getCustomProperties
     * @todo   Implement testGetCustomProperties().
     */
    public function testGetCustomProperties() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Metadata\DocInfo::isCustomPropertySet
     * @todo   Implement testIsCustomPropertySet().
     */
    public function testIsCustomPropertySet() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Metadata\DocInfo::getCustomPropertyValue
     * @todo   Implement testGetCustomPropertyValue().
     */
    public function testGetCustomPropertyValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Metadata\DocInfo::getCustomPropertyType
     * @todo   Implement testGetCustomPropertyType().
     */
    public function testGetCustomPropertyType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Metadata\DocInfo::setCustomProperty
     * @todo   Implement testSetCustomProperty().
     */
    public function testSetCustomProperty() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Metadata\DocInfo::convertProperty
     * @todo   Implement testConvertProperty().
     */
    public function testConvertProperty() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Metadata\DocInfo::convertPropertyType
     * @todo   Implement testConvertPropertyType().
     */
    public function testConvertPropertyType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
