<?php

namespace Framework\Classes\PhpWord\Shared;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:29:22.
 */
class ConverterTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Converter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Converter;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Framework\Classes\PhpWord\Shared\Converter::cmToTwip
     * @todo   Implement testCmToTwip().
     */
    public function testCmToTwip() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Shared\Converter::cmToInch
     * @todo   Implement testCmToInch().
     */
    public function testCmToInch() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Shared\Converter::cmToPixel
     * @todo   Implement testCmToPixel().
     */
    public function testCmToPixel() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Shared\Converter::cmToPoint
     * @todo   Implement testCmToPoint().
     */
    public function testCmToPoint() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Shared\Converter::cmToEmu
     * @todo   Implement testCmToEmu().
     */
    public function testCmToEmu() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Shared\Converter::inchToTwip
     * @todo   Implement testInchToTwip().
     */
    public function testInchToTwip() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Shared\Converter::inchToCm
     * @todo   Implement testInchToCm().
     */
    public function testInchToCm() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Shared\Converter::inchToPixel
     * @todo   Implement testInchToPixel().
     */
    public function testInchToPixel() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Shared\Converter::inchToPoint
     * @todo   Implement testInchToPoint().
     */
    public function testInchToPoint() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Shared\Converter::inchToEmu
     * @todo   Implement testInchToEmu().
     */
    public function testInchToEmu() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Shared\Converter::pixelToTwip
     * @todo   Implement testPixelToTwip().
     */
    public function testPixelToTwip() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Shared\Converter::pixelToCm
     * @todo   Implement testPixelToCm().
     */
    public function testPixelToCm() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Shared\Converter::pixelToPoint
     * @todo   Implement testPixelToPoint().
     */
    public function testPixelToPoint() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Shared\Converter::pixelToEmu
     * @todo   Implement testPixelToEmu().
     */
    public function testPixelToEmu() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Shared\Converter::pointToTwip
     * @todo   Implement testPointToTwip().
     */
    public function testPointToTwip() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Shared\Converter::pointToPixel
     * @todo   Implement testPointToPixel().
     */
    public function testPointToPixel() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Shared\Converter::pointToEmu
     * @todo   Implement testPointToEmu().
     */
    public function testPointToEmu() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Shared\Converter::emuToPixel
     * @todo   Implement testEmuToPixel().
     */
    public function testEmuToPixel() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Shared\Converter::degreeToAngle
     * @todo   Implement testDegreeToAngle().
     */
    public function testDegreeToAngle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Shared\Converter::angleToDegree
     * @todo   Implement testAngleToDegree().
     */
    public function testAngleToDegree() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Shared\Converter::htmlToRgb
     * @todo   Implement testHtmlToRgb().
     */
    public function testHtmlToRgb() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
