<?php

namespace Framework\Classes\PhpWord\Shared;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:29:21.
 */
class DrawingTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Drawing
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Drawing;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Framework\Classes\PhpWord\Shared\Drawing::pixelsToEMU
     * @todo   Implement testPixelsToEMU().
     */
    public function testPixelsToEMU() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Shared\Drawing::emuToPixels
     * @todo   Implement testEmuToPixels().
     */
    public function testEmuToPixels() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Shared\Drawing::pixelsToPoints
     * @todo   Implement testPixelsToPoints().
     */
    public function testPixelsToPoints() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Shared\Drawing::pointsToPixels
     * @todo   Implement testPointsToPixels().
     */
    public function testPointsToPixels() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Shared\Drawing::degreesToAngle
     * @todo   Implement testDegreesToAngle().
     */
    public function testDegreesToAngle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Shared\Drawing::angleToDegrees
     * @todo   Implement testAngleToDegrees().
     */
    public function testAngleToDegrees() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Shared\Drawing::pixelsToCentimeters
     * @todo   Implement testPixelsToCentimeters().
     */
    public function testPixelsToCentimeters() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Shared\Drawing::centimetersToPixels
     * @todo   Implement testCentimetersToPixels().
     */
    public function testCentimetersToPixels() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Shared\Drawing::centimetersToTwips
     * @todo   Implement testCentimetersToTwips().
     */
    public function testCentimetersToTwips() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Shared\Drawing::twipsToCentimeters
     * @todo   Implement testTwipsToCentimeters().
     */
    public function testTwipsToCentimeters() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Shared\Drawing::inchesToTwips
     * @todo   Implement testInchesToTwips().
     */
    public function testInchesToTwips() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Shared\Drawing::twipsToInches
     * @todo   Implement testTwipsToInches().
     */
    public function testTwipsToInches() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Shared\Drawing::twipsToPixels
     * @todo   Implement testTwipsToPixels().
     */
    public function testTwipsToPixels() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Shared\Drawing::htmlToRGB
     * @todo   Implement testHtmlToRGB().
     */
    public function testHtmlToRGB() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
