<?php

namespace Framework\Classes\PhpWord\Shared;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:29:23.
 */
class FontTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Font
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Font;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Framework\Classes\PhpWord\Shared\Font::fontSizeToPixels
     * @todo   Implement testFontSizeToPixels().
     */
    public function testFontSizeToPixels() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Shared\Font::inchSizeToPixels
     * @todo   Implement testInchSizeToPixels().
     */
    public function testInchSizeToPixels() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Shared\Font::centimeterSizeToPixels
     * @todo   Implement testCentimeterSizeToPixels().
     */
    public function testCentimeterSizeToPixels() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Shared\Font::centimeterSizeToTwips
     * @todo   Implement testCentimeterSizeToTwips().
     */
    public function testCentimeterSizeToTwips() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Shared\Font::inchSizeToTwips
     * @todo   Implement testInchSizeToTwips().
     */
    public function testInchSizeToTwips() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Shared\Font::pixelSizeToTwips
     * @todo   Implement testPixelSizeToTwips().
     */
    public function testPixelSizeToTwips() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Shared\Font::pointSizeToTwips
     * @todo   Implement testPointSizeToTwips().
     */
    public function testPointSizeToTwips() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
