<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:33:25.
 */
class PagSeguroLibraryTest extends PHPUnit_Framework_TestCase {

    /**
     * @var PagSeguroLibrary
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PagSeguroLibrary;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers PagSeguroLibrary::init
     * @todo   Implement testInit().
     */
    public function testInit() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroLibrary::getVersion
     * @todo   Implement testGetVersion().
     */
    public function testGetVersion() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroLibrary::getPath
     * @todo   Implement testGetPath().
     */
    public function testGetPath() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroLibrary::getModuleVersion
     * @todo   Implement testGetModuleVersion().
     */
    public function testGetModuleVersion() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroLibrary::setModuleVersion
     * @todo   Implement testSetModuleVersion().
     */
    public function testSetModuleVersion() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroLibrary::getPHPVersion
     * @todo   Implement testGetPHPVersion().
     */
    public function testGetPHPVersion() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroLibrary::setPHPVersion
     * @todo   Implement testSetPHPVersion().
     */
    public function testSetPHPVersion() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroLibrary::getCMSVersion
     * @todo   Implement testGetCMSVersion().
     */
    public function testGetCMSVersion() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroLibrary::setCMSVersion
     * @todo   Implement testSetCMSVersion().
     */
    public function testSetCMSVersion() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
