<?php

namespace Framework\Classes\PhpWord;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:27:49.
 */
class IOFactoryTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var IOFactory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new IOFactory;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Framework\Classes\PhpWord\IOFactory::createWriter
     * @todo   Implement testCreateWriter().
     */
    public function testCreateWriter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\IOFactory::createReader
     * @todo   Implement testCreateReader().
     */
    public function testCreateReader() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\IOFactory::load
     * @todo   Implement testLoad().
     */
    public function testLoad() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
