<?php

namespace Framework\Classes\PhpWord;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:27:48.
 */
class PhpWordTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var PhpWord
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PhpWord;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Framework\Classes\PhpWord\PhpWord::__call
     * @todo   Implement test__call().
     */
    public function test__call() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\PhpWord::getDocInfo
     * @todo   Implement testGetDocInfo().
     */
    public function testGetDocInfo() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\PhpWord::getProtection
     * @todo   Implement testGetProtection().
     */
    public function testGetProtection() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\PhpWord::getCompatibility
     * @todo   Implement testGetCompatibility().
     */
    public function testGetCompatibility() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\PhpWord::getSections
     * @todo   Implement testGetSections().
     */
    public function testGetSections() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\PhpWord::addSection
     * @todo   Implement testAddSection().
     */
    public function testAddSection() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\PhpWord::getDefaultFontName
     * @todo   Implement testGetDefaultFontName().
     */
    public function testGetDefaultFontName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\PhpWord::setDefaultFontName
     * @todo   Implement testSetDefaultFontName().
     */
    public function testSetDefaultFontName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\PhpWord::getDefaultFontSize
     * @todo   Implement testGetDefaultFontSize().
     */
    public function testGetDefaultFontSize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\PhpWord::setDefaultFontSize
     * @todo   Implement testSetDefaultFontSize().
     */
    public function testSetDefaultFontSize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\PhpWord::setDefaultParagraphStyle
     * @todo   Implement testSetDefaultParagraphStyle().
     */
    public function testSetDefaultParagraphStyle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\PhpWord::loadTemplate
     * @todo   Implement testLoadTemplate().
     */
    public function testLoadTemplate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\PhpWord::save
     * @todo   Implement testSave().
     */
    public function testSave() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\PhpWord::createSection
     * @todo   Implement testCreateSection().
     */
    public function testCreateSection() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\PhpWord::getDocumentProperties
     * @todo   Implement testGetDocumentProperties().
     */
    public function testGetDocumentProperties() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\PhpWord::setDocumentProperties
     * @todo   Implement testSetDocumentProperties().
     */
    public function testSetDocumentProperties() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
