<?php

namespace Framework\Classes\PhpWord;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:29:24.
 */
class SettingsTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Settings
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Settings;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Framework\Classes\PhpWord\Settings::hasCompatibility
     * @todo   Implement testHasCompatibility().
     */
    public function testHasCompatibility() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Settings::setCompatibility
     * @todo   Implement testSetCompatibility().
     */
    public function testSetCompatibility() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Settings::getZipClass
     * @todo   Implement testGetZipClass().
     */
    public function testGetZipClass() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Settings::setZipClass
     * @todo   Implement testSetZipClass().
     */
    public function testSetZipClass() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Settings::setPdfRenderer
     * @todo   Implement testSetPdfRenderer().
     */
    public function testSetPdfRenderer() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Settings::getPdfRendererName
     * @todo   Implement testGetPdfRendererName().
     */
    public function testGetPdfRendererName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Settings::setPdfRendererName
     * @todo   Implement testSetPdfRendererName().
     */
    public function testSetPdfRendererName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Settings::getPdfRendererPath
     * @todo   Implement testGetPdfRendererPath().
     */
    public function testGetPdfRendererPath() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Settings::setPdfRendererPath
     * @todo   Implement testSetPdfRendererPath().
     */
    public function testSetPdfRendererPath() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Settings::getMeasurementUnit
     * @todo   Implement testGetMeasurementUnit().
     */
    public function testGetMeasurementUnit() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Settings::setMeasurementUnit
     * @todo   Implement testSetMeasurementUnit().
     */
    public function testSetMeasurementUnit() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Settings::setTempDir
     * @todo   Implement testSetTempDir().
     */
    public function testSetTempDir() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Settings::getTempDir
     * @todo   Implement testGetTempDir().
     */
    public function testGetTempDir() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Settings::getDefaultFontName
     * @todo   Implement testGetDefaultFontName().
     */
    public function testGetDefaultFontName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Settings::setDefaultFontName
     * @todo   Implement testSetDefaultFontName().
     */
    public function testSetDefaultFontName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Settings::getDefaultFontSize
     * @todo   Implement testGetDefaultFontSize().
     */
    public function testGetDefaultFontSize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Settings::setDefaultFontSize
     * @todo   Implement testSetDefaultFontSize().
     */
    public function testSetDefaultFontSize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Settings::loadConfig
     * @todo   Implement testLoadConfig().
     */
    public function testLoadConfig() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Settings::getCompatibility
     * @todo   Implement testGetCompatibility().
     */
    public function testGetCompatibility() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
