<?php

namespace Framework\Classes\PhpWord;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:27:50.
 */
class StyleTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Style
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Style;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Framework\Classes\PhpWord\Style::addParagraphStyle
     * @todo   Implement testAddParagraphStyle().
     */
    public function testAddParagraphStyle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Style::addFontStyle
     * @todo   Implement testAddFontStyle().
     */
    public function testAddFontStyle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Style::addLinkStyle
     * @todo   Implement testAddLinkStyle().
     */
    public function testAddLinkStyle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Style::addNumberingStyle
     * @todo   Implement testAddNumberingStyle().
     */
    public function testAddNumberingStyle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Style::addTitleStyle
     * @todo   Implement testAddTitleStyle().
     */
    public function testAddTitleStyle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Style::addTableStyle
     * @todo   Implement testAddTableStyle().
     */
    public function testAddTableStyle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Style::countStyles
     * @todo   Implement testCountStyles().
     */
    public function testCountStyles() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Style::resetStyles
     * @todo   Implement testResetStyles().
     */
    public function testResetStyles() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Style::setDefaultParagraphStyle
     * @todo   Implement testSetDefaultParagraphStyle().
     */
    public function testSetDefaultParagraphStyle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Style::getStyles
     * @todo   Implement testGetStyles().
     */
    public function testGetStyles() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\Style::getStyle
     * @todo   Implement testGetStyle().
     */
    public function testGetStyle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
