<?php

namespace Framework\Classes\PhpWord;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:27:34.
 */
class TemplateProcessorTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var TemplateProcessor
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new TemplateProcessor;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Framework\Classes\PhpWord\TemplateProcessor::applyXslStyleSheet
     * @todo   Implement testApplyXslStyleSheet().
     */
    public function testApplyXslStyleSheet() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\TemplateProcessor::setValue
     * @todo   Implement testSetValue().
     */
    public function testSetValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\TemplateProcessor::getVariables
     * @todo   Implement testGetVariables().
     */
    public function testGetVariables() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\TemplateProcessor::cloneRow
     * @todo   Implement testCloneRow().
     */
    public function testCloneRow() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\TemplateProcessor::cloneBlock
     * @todo   Implement testCloneBlock().
     */
    public function testCloneBlock() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\TemplateProcessor::replaceBlock
     * @todo   Implement testReplaceBlock().
     */
    public function testReplaceBlock() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\TemplateProcessor::deleteBlock
     * @todo   Implement testDeleteBlock().
     */
    public function testDeleteBlock() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\TemplateProcessor::save
     * @todo   Implement testSave().
     */
    public function testSave() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\PhpWord\TemplateProcessor::saveAs
     * @todo   Implement testSaveAs().
     */
    public function testSaveAs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
