<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:33:18.
 */
class Minify_Controller_BaseTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Minify_Controller_Base
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Minify_Controller_Base;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Minify_Controller_Base::getDefaultMinifyOptions
     * @todo   Implement testGetDefaultMinifyOptions().
     */
    public function testGetDefaultMinifyOptions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Minify_Controller_Base::getDefaultMinifers
     * @todo   Implement testGetDefaultMinifers().
     */
    public function testGetDefaultMinifers() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Minify_Controller_Base::_fileIsSafe
     * @todo   Implement test_fileIsSafe().
     */
    public function test_fileIsSafe() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Minify_Controller_Base::checkAllowDirs
     * @todo   Implement testCheckAllowDirs().
     */
    public function testCheckAllowDirs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Minify_Controller_Base::checkNotHidden
     * @todo   Implement testCheckNotHidden().
     */
    public function testCheckNotHidden() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Minify_Controller_Base::mixInDefaultOptions
     * @todo   Implement testMixInDefaultOptions().
     */
    public function testMixInDefaultOptions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Minify_Controller_Base::analyzeSources
     * @todo   Implement testAnalyzeSources().
     */
    public function testAnalyzeSources() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Minify_Controller_Base::log
     * @todo   Implement testLog().
     */
    public function testLog() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
