<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:33:11.
 */
class Minify_JS_ClosureCompilerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Minify_JS_ClosureCompiler
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Minify_JS_ClosureCompiler;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Minify_JS_ClosureCompiler::minify
     * @todo   Implement testMinify().
     */
    public function testMinify() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Minify_JS_ClosureCompiler::min
     * @todo   Implement testMin().
     */
    public function testMin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
