<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:34:03.
 */
class PagSeguroServiceExceptionTest extends PHPUnit_Framework_TestCase {

    /**
     * @var PagSeguroServiceException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PagSeguroServiceException;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers PagSeguroServiceException::getErrors
     * @todo   Implement testGetErrors().
     */
    public function testGetErrors() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroServiceException::setErrors
     * @todo   Implement testSetErrors().
     */
    public function testSetErrors() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroServiceException::getHttpStatus
     * @todo   Implement testGetHttpStatus().
     */
    public function testGetHttpStatus() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroServiceException::setHttpStatus
     * @todo   Implement testSetHttpStatus().
     */
    public function testSetHttpStatus() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroServiceException::getFormattedMessage
     * @todo   Implement testGetFormattedMessage().
     */
    public function testGetFormattedMessage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PagSeguroServiceException::getOneLineMessage
     * @todo   Implement testGetOneLineMessage().
     */
    public function testGetOneLineMessage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
