<?php

namespace Framework\Classes\PhpWord\Writer\Word2007\Style;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:28:25.
 */
class AbstractStyleTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var AbstractStyle
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new AbstractStyle;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}
