<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:33:23.
 */
class PHPlotTest extends PHPUnit_Framework_TestCase {

    /**
     * @var PHPlot
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PHPlot;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers PHPlot::SetInputFile
     * @todo   Implement testSetInputFile().
     */
    public function testSetInputFile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetBackgroundColor
     * @todo   Implement testSetBackgroundColor().
     */
    public function testSetBackgroundColor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetPlotBgColor
     * @todo   Implement testSetPlotBgColor().
     */
    public function testSetPlotBgColor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetTitleColor
     * @todo   Implement testSetTitleColor().
     */
    public function testSetTitleColor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetXTitleColor
     * @todo   Implement testSetXTitleColor().
     */
    public function testSetXTitleColor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetYTitleColor
     * @todo   Implement testSetYTitleColor().
     */
    public function testSetYTitleColor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetTickColor
     * @todo   Implement testSetTickColor().
     */
    public function testSetTickColor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetLabelColor
     * @todo   Implement testSetLabelColor().
     */
    public function testSetLabelColor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetTextColor
     * @todo   Implement testSetTextColor().
     */
    public function testSetTextColor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetLightGridColor
     * @todo   Implement testSetLightGridColor().
     */
    public function testSetLightGridColor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetGridColor
     * @todo   Implement testSetGridColor().
     */
    public function testSetGridColor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetImageBorderColor
     * @todo   Implement testSetImageBorderColor().
     */
    public function testSetImageBorderColor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetTransparentColor
     * @todo   Implement testSetTransparentColor().
     */
    public function testSetTransparentColor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetRGBArray
     * @todo   Implement testSetRGBArray().
     */
    public function testSetRGBArray() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetRGBColor
     * @todo   Implement testSetRGBColor().
     */
    public function testSetRGBColor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetDataColors
     * @todo   Implement testSetDataColors().
     */
    public function testSetDataColors() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetDataBorderColors
     * @todo   Implement testSetDataBorderColors().
     */
    public function testSetDataBorderColors() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetErrorBarColors
     * @todo   Implement testSetErrorBarColors().
     */
    public function testSetErrorBarColors() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetDefaultDashedStyle
     * @todo   Implement testSetDefaultDashedStyle().
     */
    public function testSetDefaultDashedStyle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetLineWidths
     * @todo   Implement testSetLineWidths().
     */
    public function testSetLineWidths() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetLineStyles
     * @todo   Implement testSetLineStyles().
     */
    public function testSetLineStyles() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetLineSpacing
     * @todo   Implement testSetLineSpacing().
     */
    public function testSetLineSpacing() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetUseTTF
     * @todo   Implement testSetUseTTF().
     */
    public function testSetUseTTF() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetTTFPath
     * @todo   Implement testSetTTFPath().
     */
    public function testSetTTFPath() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetDefaultTTFont
     * @todo   Implement testSetDefaultTTFont().
     */
    public function testSetDefaultTTFont() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetFontGD
     * @todo   Implement testSetFontGD().
     */
    public function testSetFontGD() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetFontTTF
     * @todo   Implement testSetFontTTF().
     */
    public function testSetFontTTF() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetFont
     * @todo   Implement testSetFont().
     */
    public function testSetFont() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::DrawText
     * @todo   Implement testDrawText().
     */
    public function testDrawText() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SizeText
     * @todo   Implement testSizeText().
     */
    public function testSizeText() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetFileFormat
     * @todo   Implement testSetFileFormat().
     */
    public function testSetFileFormat() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetBgImage
     * @todo   Implement testSetBgImage().
     */
    public function testSetBgImage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetPlotAreaBgImage
     * @todo   Implement testSetPlotAreaBgImage().
     */
    public function testSetPlotAreaBgImage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetOutputFile
     * @todo   Implement testSetOutputFile().
     */
    public function testSetOutputFile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetIsInline
     * @todo   Implement testSetIsInline().
     */
    public function testSetIsInline() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::PrintImage
     * @todo   Implement testPrintImage().
     */
    public function testPrintImage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::EncodeImage
     * @todo   Implement testEncodeImage().
     */
    public function testEncodeImage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetFailureImage
     * @todo   Implement testSetFailureImage().
     */
    public function testSetFailureImage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetXDataLabelPos
     * @todo   Implement testSetXDataLabelPos().
     */
    public function testSetXDataLabelPos() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetYDataLabelPos
     * @todo   Implement testSetYDataLabelPos().
     */
    public function testSetYDataLabelPos() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetXTickLabelPos
     * @todo   Implement testSetXTickLabelPos().
     */
    public function testSetXTickLabelPos() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetYTickLabelPos
     * @todo   Implement testSetYTickLabelPos().
     */
    public function testSetYTickLabelPos() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetXLabelType
     * @todo   Implement testSetXLabelType().
     */
    public function testSetXLabelType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetXDataLabelType
     * @todo   Implement testSetXDataLabelType().
     */
    public function testSetXDataLabelType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetYLabelType
     * @todo   Implement testSetYLabelType().
     */
    public function testSetYLabelType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetYDataLabelType
     * @todo   Implement testSetYDataLabelType().
     */
    public function testSetYDataLabelType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetXTimeFormat
     * @todo   Implement testSetXTimeFormat().
     */
    public function testSetXTimeFormat() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetYTimeFormat
     * @todo   Implement testSetYTimeFormat().
     */
    public function testSetYTimeFormat() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetNumberFormat
     * @todo   Implement testSetNumberFormat().
     */
    public function testSetNumberFormat() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetXLabelAngle
     * @todo   Implement testSetXLabelAngle().
     */
    public function testSetXLabelAngle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetYLabelAngle
     * @todo   Implement testSetYLabelAngle().
     */
    public function testSetYLabelAngle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetXDataLabelAngle
     * @todo   Implement testSetXDataLabelAngle().
     */
    public function testSetXDataLabelAngle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetYDataLabelAngle
     * @todo   Implement testSetYDataLabelAngle().
     */
    public function testSetYDataLabelAngle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetBrowserCache
     * @todo   Implement testSetBrowserCache().
     */
    public function testSetBrowserCache() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetPrintImage
     * @todo   Implement testSetPrintImage().
     */
    public function testSetPrintImage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetPlotBorderType
     * @todo   Implement testSetPlotBorderType().
     */
    public function testSetPlotBorderType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetImageBorderType
     * @todo   Implement testSetImageBorderType().
     */
    public function testSetImageBorderType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetImageBorderWidth
     * @todo   Implement testSetImageBorderWidth().
     */
    public function testSetImageBorderWidth() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetDrawPlotAreaBackground
     * @todo   Implement testSetDrawPlotAreaBackground().
     */
    public function testSetDrawPlotAreaBackground() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetDrawXGrid
     * @todo   Implement testSetDrawXGrid().
     */
    public function testSetDrawXGrid() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetDrawYGrid
     * @todo   Implement testSetDrawYGrid().
     */
    public function testSetDrawYGrid() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetDrawDashedGrid
     * @todo   Implement testSetDrawDashedGrid().
     */
    public function testSetDrawDashedGrid() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetDrawXDataLabelLines
     * @todo   Implement testSetDrawXDataLabelLines().
     */
    public function testSetDrawXDataLabelLines() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetTitle
     * @todo   Implement testSetTitle().
     */
    public function testSetTitle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetXTitle
     * @todo   Implement testSetXTitle().
     */
    public function testSetXTitle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetYTitle
     * @todo   Implement testSetYTitle().
     */
    public function testSetYTitle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetShading
     * @todo   Implement testSetShading().
     */
    public function testSetShading() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetPlotType
     * @todo   Implement testSetPlotType().
     */
    public function testSetPlotType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetXAxisPosition
     * @todo   Implement testSetXAxisPosition().
     */
    public function testSetXAxisPosition() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetYAxisPosition
     * @todo   Implement testSetYAxisPosition().
     */
    public function testSetYAxisPosition() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetDrawXAxis
     * @todo   Implement testSetDrawXAxis().
     */
    public function testSetDrawXAxis() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetDrawYAxis
     * @todo   Implement testSetDrawYAxis().
     */
    public function testSetDrawYAxis() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetXScaleType
     * @todo   Implement testSetXScaleType().
     */
    public function testSetXScaleType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetYScaleType
     * @todo   Implement testSetYScaleType().
     */
    public function testSetYScaleType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetPrecisionX
     * @todo   Implement testSetPrecisionX().
     */
    public function testSetPrecisionX() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetPrecisionY
     * @todo   Implement testSetPrecisionY().
     */
    public function testSetPrecisionY() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetErrorBarLineWidth
     * @todo   Implement testSetErrorBarLineWidth().
     */
    public function testSetErrorBarLineWidth() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetLabelScalePosition
     * @todo   Implement testSetLabelScalePosition().
     */
    public function testSetLabelScalePosition() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetErrorBarSize
     * @todo   Implement testSetErrorBarSize().
     */
    public function testSetErrorBarSize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetErrorBarShape
     * @todo   Implement testSetErrorBarShape().
     */
    public function testSetErrorBarShape() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetPointShapes
     * @todo   Implement testSetPointShapes().
     */
    public function testSetPointShapes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetPointSizes
     * @todo   Implement testSetPointSizes().
     */
    public function testSetPointSizes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetDrawBrokenLines
     * @todo   Implement testSetDrawBrokenLines().
     */
    public function testSetDrawBrokenLines() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetDataType
     * @todo   Implement testSetDataType().
     */
    public function testSetDataType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetDataValues
     * @todo   Implement testSetDataValues().
     */
    public function testSetDataValues() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetCallback
     * @todo   Implement testSetCallback().
     */
    public function testSetCallback() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::GetCallback
     * @todo   Implement testGetCallback().
     */
    public function testGetCallback() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::RemoveCallback
     * @todo   Implement testRemoveCallback().
     */
    public function testRemoveCallback() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetMarginsPixels
     * @todo   Implement testSetMarginsPixels().
     */
    public function testSetMarginsPixels() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetPlotAreaPixels
     * @todo   Implement testSetPlotAreaPixels().
     */
    public function testSetPlotAreaPixels() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetPlotAreaWorld
     * @todo   Implement testSetPlotAreaWorld().
     */
    public function testSetPlotAreaWorld() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::xtr
     * @todo   Implement testXtr().
     */
    public function testXtr() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::ytr
     * @todo   Implement testYtr().
     */
    public function testYtr() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::GetDeviceXY
     * @todo   Implement testGetDeviceXY().
     */
    public function testGetDeviceXY() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetXTickIncrement
     * @todo   Implement testSetXTickIncrement().
     */
    public function testSetXTickIncrement() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetYTickIncrement
     * @todo   Implement testSetYTickIncrement().
     */
    public function testSetYTickIncrement() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetNumXTicks
     * @todo   Implement testSetNumXTicks().
     */
    public function testSetNumXTicks() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetNumYTicks
     * @todo   Implement testSetNumYTicks().
     */
    public function testSetNumYTicks() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetXTickPos
     * @todo   Implement testSetXTickPos().
     */
    public function testSetXTickPos() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetYTickPos
     * @todo   Implement testSetYTickPos().
     */
    public function testSetYTickPos() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetSkipTopTick
     * @todo   Implement testSetSkipTopTick().
     */
    public function testSetSkipTopTick() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetSkipBottomTick
     * @todo   Implement testSetSkipBottomTick().
     */
    public function testSetSkipBottomTick() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetSkipLeftTick
     * @todo   Implement testSetSkipLeftTick().
     */
    public function testSetSkipLeftTick() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetSkipRightTick
     * @todo   Implement testSetSkipRightTick().
     */
    public function testSetSkipRightTick() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetXTickLength
     * @todo   Implement testSetXTickLength().
     */
    public function testSetXTickLength() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetYTickLength
     * @todo   Implement testSetYTickLength().
     */
    public function testSetYTickLength() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetXTickCrossing
     * @todo   Implement testSetXTickCrossing().
     */
    public function testSetXTickCrossing() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetYTickCrossing
     * @todo   Implement testSetYTickCrossing().
     */
    public function testSetYTickCrossing() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetXTickAnchor
     * @todo   Implement testSetXTickAnchor().
     */
    public function testSetXTickAnchor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetYTickAnchor
     * @todo   Implement testSetYTickAnchor().
     */
    public function testSetYTickAnchor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetLegend
     * @todo   Implement testSetLegend().
     */
    public function testSetLegend() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetLegendPixels
     * @todo   Implement testSetLegendPixels().
     */
    public function testSetLegendPixels() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetLegendWorld
     * @todo   Implement testSetLegendWorld().
     */
    public function testSetLegendWorld() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetLegendPosition
     * @todo   Implement testSetLegendPosition().
     */
    public function testSetLegendPosition() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetLegendStyle
     * @todo   Implement testSetLegendStyle().
     */
    public function testSetLegendStyle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetLegendUseShapes
     * @todo   Implement testSetLegendUseShapes().
     */
    public function testSetLegendUseShapes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetLegendReverse
     * @todo   Implement testSetLegendReverse().
     */
    public function testSetLegendReverse() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::GetLegendSize
     * @todo   Implement testGetLegendSize().
     */
    public function testGetLegendSize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::DrawGraph
     * @todo   Implement testDrawGraph().
     */
    public function testDrawGraph() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetDrawVertTicks
     * @todo   Implement testSetDrawVertTicks().
     */
    public function testSetDrawVertTicks() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetDrawHorizTicks
     * @todo   Implement testSetDrawHorizTicks().
     */
    public function testSetDrawHorizTicks() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetNumHorizTicks
     * @todo   Implement testSetNumHorizTicks().
     */
    public function testSetNumHorizTicks() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetNumVertTicks
     * @todo   Implement testSetNumVertTicks().
     */
    public function testSetNumVertTicks() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetHorizTickIncrement
     * @todo   Implement testSetHorizTickIncrement().
     */
    public function testSetHorizTickIncrement() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetVertTickIncrement
     * @todo   Implement testSetVertTickIncrement().
     */
    public function testSetVertTickIncrement() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetVertTickPosition
     * @todo   Implement testSetVertTickPosition().
     */
    public function testSetVertTickPosition() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetHorizTickPosition
     * @todo   Implement testSetHorizTickPosition().
     */
    public function testSetHorizTickPosition() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetTitleFontSize
     * @todo   Implement testSetTitleFontSize().
     */
    public function testSetTitleFontSize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetAxisFontSize
     * @todo   Implement testSetAxisFontSize().
     */
    public function testSetAxisFontSize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetSmallFontSize
     * @todo   Implement testSetSmallFontSize().
     */
    public function testSetSmallFontSize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetXLabelFontSize
     * @todo   Implement testSetXLabelFontSize().
     */
    public function testSetXLabelFontSize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetYLabelFontSize
     * @todo   Implement testSetYLabelFontSize().
     */
    public function testSetYLabelFontSize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetXLabel
     * @todo   Implement testSetXLabel().
     */
    public function testSetXLabel() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetYLabel
     * @todo   Implement testSetYLabel().
     */
    public function testSetYLabel() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetTickLength
     * @todo   Implement testSetTickLength().
     */
    public function testSetTickLength() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetYGridLabelType
     * @todo   Implement testSetYGridLabelType().
     */
    public function testSetYGridLabelType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetXGridLabelType
     * @todo   Implement testSetXGridLabelType().
     */
    public function testSetXGridLabelType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetYGridLabelPos
     * @todo   Implement testSetYGridLabelPos().
     */
    public function testSetYGridLabelPos() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetXGridLabelPos
     * @todo   Implement testSetXGridLabelPos().
     */
    public function testSetXGridLabelPos() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetXTitlePos
     * @todo   Implement testSetXTitlePos().
     */
    public function testSetXTitlePos() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetYTitlePos
     * @todo   Implement testSetYTitlePos().
     */
    public function testSetYTitlePos() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetDrawXDataLabels
     * @todo   Implement testSetDrawXDataLabels().
     */
    public function testSetDrawXDataLabels() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetNewPlotAreaPixels
     * @todo   Implement testSetNewPlotAreaPixels().
     */
    public function testSetNewPlotAreaPixels() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetLineWidth
     * @todo   Implement testSetLineWidth().
     */
    public function testSetLineWidth() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetPointShape
     * @todo   Implement testSetPointShape().
     */
    public function testSetPointShape() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetPointSize
     * @todo   Implement testSetPointSize().
     */
    public function testSetPointSize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
