<?php

namespace Framework\Classes\PhpWord\Writer\HTML\Element;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:27:57.
 */
class AbstractElementTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var AbstractElement
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new AbstractElement;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Framework\Classes\PhpWord\Writer\HTML\Element\AbstractElement::setWithoutP
     * @todo   Implement testSetWithoutP().
     */
    public function testSetWithoutP() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
