<?php

namespace Framework\Classes\Mailer;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:29:31.
 */
class html2textTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var html2text
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new html2text;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Framework\Classes\Mailer\html2text::set_html
     * @todo   Implement testSet_html().
     */
    public function testSet_html() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\Mailer\html2text::get_text
     * @todo   Implement testGet_text().
     */
    public function testGet_text() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\Mailer\html2text::print_text
     * @todo   Implement testPrint_text().
     */
    public function testPrint_text() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\Mailer\html2text::p
     * @todo   Implement testP().
     */
    public function testP() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\Mailer\html2text::set_allowed_tags
     * @todo   Implement testSet_allowed_tags().
     */
    public function testSet_allowed_tags() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\Mailer\html2text::set_base_url
     * @todo   Implement testSet_base_url().
     */
    public function testSet_base_url() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
