<?php

namespace Framework\Classes\Mailer;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:29:30.
 */
class EasyPeasyICSTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var EasyPeasyICS
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new EasyPeasyICS;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Framework\Classes\Mailer\EasyPeasyICS::addEvent
     * @todo   Implement testAddEvent().
     */
    public function testAddEvent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Framework\Classes\Mailer\EasyPeasyICS::render
     * @todo   Implement testRender().
     */
    public function testRender() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
