<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-24 at 16:33:09.
 */
class Minify_Cache_APCTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Minify_Cache_APC
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Minify_Cache_APC;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Minify_Cache_APC::store
     * @todo   Implement testStore().
     */
    public function testStore() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Minify_Cache_APC::getSize
     * @todo   Implement testGetSize().
     */
    public function testGetSize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Minify_Cache_APC::isValid
     * @todo   Implement testIsValid().
     */
    public function testIsValid() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Minify_Cache_APC::display
     * @todo   Implement testDisplay().
     */
    public function testDisplay() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Minify_Cache_APC::fetch
     * @todo   Implement testFetch().
     */
    public function testFetch() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
